import { module, type Syllabus } from './types';

/**
 * Немецкий. A1–A2 — программа Wortkraft A2 по перечню грамматики Goethe-
 * Zertifikat A2 «Fit in Deutsch 2» (стр. 104–109). B1–B2 и C1–C2 составлены
 * по перечням Goethe-Zertifikat B1–C1 и Profile Deutsch: в пробных экзаменах
 * B1–C1 списка грамматики нет.
 */
export const GERMAN: Syllabus = {
  A: [
    module('A', 'Nomen: Genus und Numerus', [
      'der, die, das',
      'Genus an der Endung',
      'Plural: -e, -er',
      'Plural: -(e)n, -s, ohne Endung',
      'Nullartikel',
      'Komposita',
      'Eigennamen: Genitiv und von',
    ]),
    module('A', 'Artikelwörter', [
      'Bestimmter Artikel',
      'Unbestimmter Artikel',
      'Negativartikel kein',
      'Demonstrativ: dieser',
      'Welch-? Was für ein?',
      'Possessiv: mein, dein, sein, ihr, Ihr',
      'unser, euer, alle',
    ]),
    module('A', 'Kasus', [
      'Nominativ',
      'Akkusativ',
      'Dativ',
      'Verben mit Dativ',
      'Dativ und Akkusativ zusammen',
      'es gibt · глаголы с Akkusativ',
      'Deklination: Übersicht',
    ]),
    module('A', 'Pronomen', [
      'Personalpronomen: Nominativ',
      'Personalpronomen: Akkusativ',
      'Personalpronomen: Dativ',
      'Reflexivpronomen',
      'Reziprokpronomen: uns, sich',
      'Indefinitpronomen',
      'Fragepronomen',
    ]),
    module('A', 'Präsens', [
      'Regelmäßige Endungen',
      'sein und haben',
      'Besonderheiten des Stammes',
      'Vokalwechsel e → i / ie',
      'Vokalwechsel a → ä, au → äu',
      'Trennbare Verben',
      'Untrennbare Verben · Präsens für Zukunft',
    ]),
    module('A', 'Modalverben', [
      'können',
      'müssen und dürfen',
      'wollen und möchten',
      'sollen',
      'Satzklammer mit Modalverb',
      'Modalverben im Präteritum',
    ]),
    module('A', 'Perfekt', [
      'Perfekt mit haben',
      'Partizip II: regelmäßig',
      'Partizip II: unregelmäßig',
      'Perfekt mit sein',
      'Partizip trennbarer Verben',
      'Partizip ohne ge-',
      'Über Vergangenes berichten',
    ]),
    module('A', 'Präteritum, Konjunktiv II, Imperativ', [
      'war und hatte',
      'kam, sagte',
      'Perfekt oder Präteritum?',
      'möchte · hätte gern',
      'könnte — höfliche Bitte',
      'Imperativ: du-, ihr-Form',
    ]),
    module('A', 'Adjektiv', [
      'Prädikativ',
      'Adverbial',
      'Attributiv nach dem Artikel',
      'Attributiv nach ein, kein, mein',
      'Komparativ mit als',
      'Superlativ: am …-sten',
      'gern – lieber · gut – besser · viel – mehr',
    ]),
    module('A', 'Präpositionen', [
      'Zeit: an, in, um, von … bis',
      'Zeit: nach, vor, seit, bis',
      'Ort + Dativ: aus, bei, von, zu, nach',
      'Wechselpräpositionen: wo? wohin?',
      'Modal: mit, ohne, für, aus',
      'Verschmelzungen: im, am, zum, zur, ins',
      'Orte und Wege',
    ]),
    module('A', 'Satzbau', [
      'Verb an zweiter Stelle',
      'Satzklammer',
      'Verbergänzungen',
      'Wortstellung: te-ka-mo-lo',
      'Negation mit nicht',
      'nicht oder kein?',
      'Fragesatz',
    ]),
    module('A', 'Satzverbindungen', [
      'und, oder, aber',
      'denn',
      'deshalb, dann',
      'dass',
      'weil',
      'wenn · indirekte Frage',
    ]),
    module('A', 'Wortbildung und Rechtschreibung', [
      '-er und -in',
      '-ung',
      'un- und -los',
      'Großschreibung',
      'ß, ss und Umlaute',
    ]),
  ],
  B: [
    module('B', 'Vergangenheit und Zukunft', [
      ['Präteritum: regelmäßige Verben', 'machte, sagte, arbeitete'],
      ['Präteritum: unregelmäßige Verben', 'ging, kam, fand, dachte, brachte'],
      ['Perfekt oder Präteritum?', 'Mündlich und schriftlich erzählen'],
      ['Plusquamperfekt', 'hatte gemacht, war gegangen; nachdem'],
      ['Futur I', 'werden + Infinitiv: Plan, Versprechen, Vermutung'],
      ['Futur II', 'wird gemacht haben: Vermutung über Vergangenes'],
    ]),
    module('B', 'Konjunktiv', [
      ['Konjunktiv II: Gegenwart', 'würde, wäre, hätte, könnte, müsste'],
      ['Irreale Wünsche', 'Wenn ich doch … hätte! Ich wünschte, …'],
      ['Irreale Bedingungen', 'Wenn ich Zeit hätte, würde ich …'],
      ['Konjunktiv II: Vergangenheit', 'hätte gemacht, wäre gegangen'],
      ['Ratschläge und höfliche Bitten', 'Du solltest … An deiner Stelle würde ich … Würden Sie …?'],
      ['Irreale Vergleiche', 'als ob, als wenn, als + Verb'],
      ['Konjunktiv I: indirekte Rede', 'er sagt, er habe / sei / komme'],
    ]),
    module('B', 'Passiv', [
      ['Passiv Präsens und Präteritum', 'wird gebaut, wurde gebaut; von + Dativ'],
      ['Passiv Perfekt und Plusquamperfekt', 'ist gebaut worden, war gebaut worden'],
      ['Passiv mit Modalverben', 'muss repariert werden'],
      ['Zustandspassiv', 'Die Tür ist geschlossen.'],
      ['Passiversatz', 'man; sich lassen; -bar; sein + zu + Infinitiv'],
    ]),
    module('B', 'Verben', [
      ['Verben mit Präpositionen', 'warten auf, sich freuen über / auf, denken an'],
      ['da- und wo-Wörter', 'darauf, worauf, damit, womit'],
      ['Reflexive Verben: Akkusativ und Dativ', 'ich wasche mich / ich wasche mir die Hände'],
      ['Infinitiv mit zu', 'Ich habe keine Lust, … zu …; es ist wichtig, … zu …'],
      ['lassen', 'etwas machen lassen; jemanden etwas tun lassen'],
      ['brauchen … zu', 'Du brauchst nicht zu kommen.'],
      ['Modalverben: subjektive Bedeutung', 'Er muss / dürfte / könnte krank sein; soll, will'],
      ['Wechselpräpositionen: stellen / stehen, legen / liegen', 'hängen, setzen / sitzen, stecken'],
      ['Trennbare und untrennbare Präfixe', 'über-, unter-, um-, durch-, wieder-'],
      ['Nomen-Verb-Verbindungen', 'eine Entscheidung treffen, in Frage kommen'],
    ]),
    module('B', 'Nomen und Adjektiv', [
      ['n-Deklination', 'der Kunde, den Kunden, des Kunden; Herr, Name'],
      ['Genitiv', 'des Mannes, der Frau; Genitiv oder von'],
      ['Adjektivdeklination: bestimmter Artikel', 'der alte Mann, mit dem alten Mann'],
      ['Adjektivdeklination: unbestimmter Artikel', 'ein alter Mann, mit einem alten Mann'],
      ['Adjektivdeklination: ohne Artikel', 'frischer Kaffee, mit frischem Brot'],
      ['Komparativ und Superlativ vor Nomen', 'das schnellere Auto, der höchste Berg'],
      ['Adjektive als Nomen', 'der Bekannte, ein Bekannter, etwas Neues'],
      ['Partizip I und II als Adjektiv', 'das weinende Kind, die gekochten Eier'],
      ['Ordinalzahlen und Datum', 'am dritten Mai, vom 1. bis zum 5.'],
    ]),
    module('B', 'Pronomen', [
      ['Relativpronomen: Nominativ und Akkusativ', 'der Mann, der …; den …'],
      ['Relativpronomen: Dativ und Genitiv', 'dem, denen; dessen, deren'],
      ['Relativsätze mit Präposition', 'die Stadt, in der …; der Freund, mit dem …'],
      ['Relativsätze mit wo, was, wer', 'alles, was …; der Ort, wo …; Wer …, der …'],
      ['Indefinitpronomen', 'einer, keiner, welche, jemand, niemand, irgendwer'],
      ['Das Wort es', 'es regnet; es gibt; Es freut mich, dass …'],
    ]),
    module('B', 'Präpositionen', [
      ['Präpositionen mit Genitiv', 'wegen, trotz, während, statt, innerhalb, außerhalb'],
      ['Temporale Präpositionen', 'ab, seit, vor, bei, innerhalb, außerhalb, über'],
      ['Lokale Präpositionen', 'gegenüber, entlang, um … herum, durch'],
      ['Kausale und konzessive Präpositionen', 'wegen, aufgrund, dank, trotz'],
    ]),
    module('B', 'Nebensätze', [
      ['Nebensatz: Verb am Ende', 'dass, weil, wenn, ob; Nebensatz vor dem Hauptsatz'],
      ['als, wenn, wann', 'einmal in der Vergangenheit / wiederholt / Frage'],
      ['Temporale Nebensätze', 'während, bevor, nachdem, seitdem, bis, sobald, solange'],
      ['obwohl und trotzdem', 'Nebensatz und Hauptsatz'],
      ['Finale Sätze', 'damit, um … zu'],
      ['Konsekutive Sätze', 'sodass, so … dass, deshalb, also'],
      ['Modale Sätze', 'indem, dadurch dass, ohne dass, ohne … zu, (an)statt … zu'],
      ['Konditionale Sätze', 'wenn, falls, sonst'],
      ['Indirekte Fragesätze', 'Ich weiß nicht, ob / wann / wie …'],
      ['je … desto', 'Je mehr ich lerne, desto besser …'],
    ]),
    module('B', 'Satzbau und Konnektoren', [
      ['Konnektoren im Hauptsatz', 'deshalb, darum, trotzdem, sonst, außerdem, dann'],
      ['Zweiteilige Konnektoren', 'sowohl … als auch, weder … noch, entweder … oder, nicht nur … sondern auch, zwar … aber'],
      ['Wortstellung im Mittelfeld', 'Dativ vor Akkusativ; Pronomen zuerst'],
      ['Position von nicht', 'Satznegation und Teilnegation; sondern'],
    ]),
    module('B', 'Wortbildung', [
      ['Nomen aus Verben und Adjektiven', '-ung, -heit, -keit, -schaft, -e, das Lesen'],
      ['Adjektive mit Suffixen', '-ig, -lich, -isch, -bar, -sam, -voll'],
      ['Komposita', 'Bestimmungswort und Grundwort, Fugen-s'],
    ]),
  ],
  C: [
    module('C', 'Nominal- und Verbalstil', [
      ['Nominalisierung von Verben', 'untersuchen → die Untersuchung; Ergänzungen im Genitiv'],
      ['Nebensatz → Präpositionalausdruck', 'weil … → wegen; obwohl … → trotz; als … → bei'],
      ['Präpositionalausdruck → Nebensatz', 'Umformung in den Verbalstil'],
      ['Funktionsverbgefüge', 'zur Verfügung stellen, in Kraft treten, Kritik üben'],
    ]),
    module('C', 'Partizipien', [
      ['Erweiterte Partizipialattribute', 'die seit Jahren steigenden Preise'],
      ['Partizipialattribut ↔ Relativsatz', 'Umformung in beide Richtungen'],
      ['Gerundivum', 'die zu lösende Aufgabe'],
      ['Partizipialkonstruktionen', 'In Berlin angekommen, …; genau genommen'],
    ]),
    module('C', 'Passiv und Alternativen', [
      ['Passiv in allen Zeiten', 'wird gebaut werden, soll gebaut worden sein'],
      ['Passiv mit Modalverben in der Vergangenheit', 'hätte gemacht werden müssen'],
      ['Passiversatzformen', 'sich lassen, sein + zu, -bar, -lich, bekommen-Passiv'],
      ['Unpersönliches Passiv', 'Hier wird nicht geraucht. Es wird getanzt.'],
    ]),
    module('C', 'Modalität', [
      ['Subjektive Modalverben in der Vergangenheit', 'Er muss / kann / dürfte es gewusst haben.'],
      ['sollen und wollen: fremde Behauptung', 'Er soll reich sein. Sie will es gesehen haben.'],
      ['Modalverbähnliche Verben', 'scheinen zu, drohen zu, versprechen zu, pflegen zu'],
      ['haben / sein + zu + Infinitiv', 'Du hast zu gehorchen. Das ist nicht zu ändern.'],
      ['Futur zur Vermutung', 'Er wird wohl krank sein. Sie wird es vergessen haben.'],
      ['Modalpartikeln', 'doch, ja, mal, eben, halt, wohl, schon, eigentlich'],
    ]),
    module('C', 'Konjunktiv', [
      ['Konjunktiv I: alle Formen', 'sei, habe, werde; Ersatz durch Konjunktiv II'],
      ['Redewiedergabe in Texten', 'Redeeinleitende Verben; Zeitstufen in der indirekten Rede'],
      ['Konjunktiv II: Präteritalformen', 'gäbe, käme, ginge, wüsste, bräuchte'],
      ['Irreale Folgesätze', 'zu …, als dass; ohne dass; als ob mit Vergangenheit'],
      ['Konjunktiv II in höflicher und distanzierter Rede', 'Ich würde meinen …; Es wäre zu überlegen'],
    ]),
    module('C', 'Komplexe Sätze', [
      ['Konnektoren: Gegensatz', 'hingegen, wohingegen, während, dagegen, allerdings'],
      ['Konnektoren: Folge und Grund', 'infolgedessen, demzufolge, folglich, zumal, da'],
      ['Konnektoren: Bedingung und Einschränkung', 'sofern, soweit, insofern als, es sei denn, vorausgesetzt'],
      ['Konzessive Sätze', 'wenn auch, auch wenn, so … auch, wie … auch'],
      ['Infinitivsätze in allen Zeiten', 'gesehen zu haben, gefragt zu werden, gelobt worden zu sein'],
      ['Satzgliedstellung und Hervorhebung', 'Vorfeld, Nachfeld, Ausklammerung'],
      ['Korrelate', 'darauf …, dass; es …, dass; dafür …, zu'],
    ]),
    module('C', 'Präpositionen und Rektion', [
      ['Präpositionen mit Genitiv (gehoben)', 'angesichts, aufgrund, bezüglich, zwecks, ungeachtet, zufolge, mangels'],
      ['Nachgestellte Präpositionen', 'der Sache wegen, dem Bericht zufolge, meiner Meinung nach'],
      ['Verben mit Genitiv', 'bedürfen, gedenken, sich einer Sache bewusst sein'],
      ['Adjektive mit Präposition', 'stolz auf, abhängig von, zuständig für'],
      ['Nomen mit Präposition', 'Interesse an, Angst vor, Rücksicht auf'],
    ]),
    module('C', 'Wortbildung und Stil', [
      ['Verbpräfixe: be-, ver-, zer-, ent-, er-', 'Bedeutungsveränderung: bearbeiten, verarbeiten'],
      ['Adjektivbildung', '-haft, -mäßig, -artig, -weise; zusammengesetzte Adjektive'],
      ['Fremdwörter und Suffixe', '-ität, -ismus, -ieren, -ant'],
      ['Textverweise', 'Pronominaladverbien, dieser / jener, Ersteres / Letzteres'],
      ['Register', 'Umgangssprache, Standardsprache, Schriftsprache'],
    ]),
  ],
};
