import { module, type Syllabus } from './types';

/**
 * Английский — по схеме Murphy: «Essential Grammar in Use» для A1–A2 и
 * «English Grammar in Use» для B1–B2; C1–C2 — по Hewings, «Advanced Grammar
 * in Use». Названия и группировка свои, темы и их ступени — как в книгах.
 */
export const ENGLISH: Syllabus = {
  A: [
    module('A', 'Present', [
      ['am / is / are', 'positive, negative, short forms'],
      ['am / is / are: questions', 'Are you …? Where is …? short answers'],
      ['Present continuous', 'I am doing; spelling of -ing'],
      ['Present continuous: questions', 'Are you working? What is she doing?'],
      ['Present simple', 'I work / she works; spelling of -s'],
      ["Present simple: negative", "I don't / she doesn't"],
      ['Present simple: questions', 'Do you …? Does he …?'],
      ['Present simple or continuous?', 'I do / I am doing; state verbs'],
      ['have got and have', "I've got / I have; questions and negatives"],
    ]),
    module('A', 'Past', [
      ['was / were', 'positive, negative, questions'],
      ['Past simple: regular and irregular', 'worked, went; spelling of -ed'],
      ['Past simple: negative and questions', "didn't; Did you …?"],
      ['Past continuous', 'I was doing'],
      ['Past simple or past continuous?', 'I was doing when … happened'],
      ['used to', 'I used to play; did you use to'],
    ]),
    module('A', 'Present perfect', [
      ['Present perfect', 'I have done; past participles'],
      ['just, already, yet', "I've just eaten; Have you finished yet?"],
      ['ever and never', 'Have you ever been …?'],
      ['How long have you …?', 'present perfect with for and since'],
      ['for, since and ago', 'for three days, since Monday, three days ago'],
      ['Present perfect or past simple?', "I've lost / I lost; finished time"],
    ]),
    module('A', 'Passive', [
      ['Passive: present and past', 'is made, was built; by'],
      ['Passive: continuous and perfect', 'is being done, has been done'],
    ]),
    module('A', 'Future', [
      ['Present continuous for the future', "What are you doing tomorrow?"],
      ['going to', "I'm going to …; it's going to rain"],
      ['will', "I'll …; predictions; I think … will"],
      ['will and shall: offers and decisions', "I'll help you; Shall I …?"],
    ]),
    module('A', 'Modal verbs', [
      ['can and could', 'ability, requests, permission'],
      ['might', 'possibility: it might rain'],
      ['must', "must / mustn't"],
      ['have to', "I have to / I don't have to"],
      ['should', 'advice: you should …'],
      ["would like", "I'd like …; Would you like …?"],
      ['Imperative and let\'s', "Do this! Don't do that! Let's go."],
    ]),
    module('A', 'there and it', [
      ['there is / there are', 'Is there …? There are some …'],
      ['there was / there were', 'There has been …, there will be …'],
      ['it', "It's cold. It's ten o'clock. It's hard to …"],
    ]),
    module('A', 'Auxiliary verbs', [
      ['Short answers', "Yes, I do. No, she isn't."],
      ['Reply questions', 'Have you? Are you? Did she?'],
      ['too and either', "I am too. I don't either."],
      ['so and neither', 'So am I. Neither do I.'],
    ]),
    module('A', 'Questions', [
      ['Word order in questions', 'Is it …? Do they …?'],
      ['Who saw you? / Who did you see?', 'subject and object questions'],
      ['Questions with prepositions', 'Who is she talking to? What is it about?'],
      ['What, which, how', 'What kind? Which one? How big?'],
      ['How long does it take?', 'It takes … to …'],
      ['Indirect questions', 'Do you know where … is?'],
    ]),
    module('A', 'Reported speech', [
      ['said and told', 'She said that … He told me that …'],
    ]),
    module('A', '-ing and to', [
      ['work / working / worked', 'forms after auxiliaries'],
      ['Verb + to', 'I want to go; I decided to …'],
      ['Verb + -ing', 'I enjoy swimming; I finished reading'],
      ['to … for purpose', 'I went to the shop to buy …'],
      ['go to, go on, go for, go -ing', 'go shopping, go on holiday'],
      ['get', 'get a job, get tired, get home'],
      ['do and make', 'do homework, make a mistake'],
      ['have', 'have breakfast, have a shower'],
    ]),
    module('A', 'Pronouns and possessives', [
      ['I / me, he / him', 'subject and object pronouns'],
      ['my / his / their', 'possessive adjectives'],
      ['mine / yours', "Whose is this? It's mine."],
      ['myself / yourself', 'reflexive pronouns; by myself'],
      ["-'s", "Kate's camera; my parents' house"],
    ]),
    module('A', 'Articles and nouns', [
      ['a / an', 'a book, an umbrella; jobs'],
      ['Singular and plural', 'flowers, children, people, scissors'],
      ['Countable and uncountable', 'a bottle / some water'],
      ['a / an or the', 'first mention, the only one'],
      ['the', 'the sun, the cinema, play the piano'],
      ['No article', 'go to work, go home, at school'],
      ['General meaning', 'I like music; I hate exams'],
      ['the with place names', 'the Alps, the USA, Paris'],
    ]),
    module('A', 'Determiners and quantifiers', [
      ['this / that / these / those', 'near and far'],
      ['one and ones', 'this one, the red ones'],
      ['some and any', 'questions, negatives, offers'],
      ['no, none, not any', "There's no …; none of them"],
      ['somebody, anything, nowhere', 'some-, any-, no-, every- words'],
      ['every and all', 'every day / all day'],
      ['all, most, some, none', 'all of them, most people'],
      ['both, either, neither', 'both of us, either day'],
      ['much, many, a lot', 'How much / how many'],
      ['a little, a few', 'little / a little, few / a few'],
    ]),
    module('A', 'Adjectives and adverbs', [
      ['Adjectives', 'position; a nice day, the day is nice'],
      ['Adverbs of manner', 'quickly, badly, well'],
      ['Comparatives', 'older, more expensive, better'],
      ['than and as … as', 'older than me; not as tall as'],
      ['Superlatives', 'the oldest, the most expensive, the best'],
      ['enough', 'old enough, enough money'],
      ['too', 'too hot, too much'],
    ]),
    module('A', 'Word order', [
      ['Verb + object, place, time', 'She speaks English very well.'],
      ['always, usually, often', 'adverbs of frequency'],
      ['still, yet, already', 'position and meaning'],
      ['Give me that book!', 'give it to me; two objects'],
    ]),
    module('A', 'Linking and clauses', [
      ['and, but, or, so, because', 'linking two sentences'],
      ['when', 'When I got home, …'],
      ['First conditional', 'If it rains, we will …'],
      ['Second conditional', 'If I had …, I would …'],
      ['Relative clauses: who, that, which', 'a person who …, a thing that …'],
      ['Relative clauses without who / that', 'the people we met'],
    ]),
    module('A', 'Prepositions', [
      ['at, on, in: time', "at 8 o'clock, on Monday, in April"],
      ['from, until, since, for', 'time periods'],
      ['before, after, during, while', 'before lunch, while I was …'],
      ['in, at, on: place', 'in the room, at the station, on the wall'],
      ['to, in, at', 'go to, arrive in, be at'],
      ['next to, between, under', 'position'],
      ['up, over, through', 'movement'],
      ['on, at, by, with, about', 'on holiday, by car, a book about …'],
      ['Adjective + preposition', 'afraid of, good at, interested in'],
      ['Verb + preposition', 'listen to, look at, wait for'],
    ]),
    module('A', 'Phrasal verbs', [
      ['Phrasal verbs: movement', 'go in, fall off, run away, come back'],
      ['Phrasal verbs with objects', 'put on your shoes / put them on'],
    ]),
  ],
  B: [
    module('B', 'Present and past', [
      ['Present continuous and present simple', 'temporary / permanent; state verbs'],
      ['Past simple and past continuous', 'interrupted actions, background'],
      ['Present perfect', 'result, experience, recent news'],
      ['Present perfect continuous', 'I have been doing; how long'],
      ['Present perfect simple or continuous?', 'result or activity'],
      ['for, since, how long', 'How long have you …? When did …?'],
      ['Present perfect or past simple?', 'unfinished and finished time'],
      ['Past perfect', 'I had done'],
      ['Past perfect continuous', 'I had been doing'],
      ['used to and would', 'past habits and states'],
    ]),
    module('B', 'Future', [
      ['Present tenses for the future', 'arrangements and timetables'],
      ['going to and will', 'plans, decisions, predictions'],
      ['Future continuous and future perfect', 'will be doing, will have done'],
      ['when I do / when I have done', 'time clauses about the future'],
      ['if and when', 'if it rains / when it rains'],
    ]),
    module('B', 'Modal verbs', [
      ['can, could, be able to', 'ability in the past; managed to'],
      ['could and could have', 'possibility and unreal past'],
      ["must and can't", 'deduction: must be, can\'t have been'],
      ['may and might', 'may have, might have'],
      ['have to and must', 'obligation; don\'t have to'],
      ["must, mustn't, needn't", "needn't have / didn't need to"],
      ['should', 'should have done; should in that-clauses'],
      ["had better, it's time", "You'd better …; It's time we went"],
      ['would', 'imagined situations; past habit'],
      ['Requests, offers, permission', 'Could you …? Would you mind …?'],
    ]),
    module('B', 'Conditionals and wish', [
      ['if I do and if I did', 'real and unreal conditions'],
      ['if I knew, I wish I knew', 'unreal present'],
      ['if I had known, I wish I had known', 'unreal past'],
      ['wish', 'I wish you would …'],
      ['unless, as long as, provided', 'conditions'],
      ['in case', 'take an umbrella in case it rains'],
    ]),
    module('B', 'Passive', [
      ['Passive forms', 'all tenses; by'],
      ['Passive with two objects', 'I was given …; be born'],
      ['it is said that / he is said to', 'reporting with the passive'],
      ['have something done', 'I had my hair cut'],
    ]),
    module('B', 'Reported speech', [
      ['Reported statements', 'tense changes; say and tell'],
      ['Reported questions and commands', 'asked if …; told me to …'],
    ]),
    module('B', 'Questions and auxiliaries', [
      ['Questions', 'subject questions, prepositions at the end'],
      ['Indirect questions', 'Do you know …? I wonder …'],
      ['I think so, I hope not', 'so and not after verbs'],
      ['Question tags', "isn't it? did you? will you?"],
    ]),
    module('B', '-ing and infinitive', [
      ['Verb + -ing', 'avoid, enjoy, mind, suggest'],
      ['Verb + to', 'decide, hope, manage, refuse'],
      ['Verb + object + to', 'I want you to …; make and let'],
      ['-ing or to: change of meaning', 'remember, stop, try, regret'],
      ['like, love, prefer, would rather', 'I prefer … to …; I\'d rather …'],
      ['Preposition + -ing', 'good at swimming; instead of going'],
      ['be used to and get used to', "I'm used to getting up early"],
      ['Verb + preposition + -ing', 'think of doing; insist on paying'],
      ["it's worth, there's no point", 'expressions + -ing'],
      ['to, for and so that', 'purpose'],
      ['Adjective + to', "easy to understand; afraid to / afraid of"],
      ['see somebody do / doing', 'verbs of perception'],
      ['-ing clauses', 'Feeling tired, I …; having finished'],
    ]),
    module('B', 'Articles and nouns', [
      ['Countable and uncountable', 'advice, information, news; a glass / glass'],
      ['a / an, some and the', 'first and second mention'],
      ['the: general and specific', 'children / the children'],
      ['the with institutions', 'school / the school, hospital, prison'],
      ['Names with and without the', 'streets, buildings, countries'],
      ['Singular and plural', 'the police are; a pair of'],
      ['Noun + noun', 'a tennis ball, a two-hour journey'],
      ["-'s and of", "my sister's name; the name of the street"],
    ]),
    module('B', 'Pronouns and determiners', [
      ['Reflexive pronouns', 'myself; each other; by myself'],
      ['a friend of mine, on my own', 'possessive structures'],
      ['there and it', 'There\'s … / It\'s …'],
      ['some, any, no, none', 'somebody, any time, no one'],
      ['much, many, little, few, plenty', 'quantity'],
      ['all, most, none of', 'all of us, most of the time'],
      ['both, neither, either', 'both of them; neither … nor'],
      ['all, every, whole, each', 'all day / every day / the whole day'],
    ]),
    module('B', 'Relative clauses', [
      ['who, that, which', 'defining relative clauses'],
      ['Clauses without who / that', 'the book I read'],
      ['whose, whom, where', 'the man whose car …'],
      ['Extra information clauses', 'non-defining, commas; which for a whole sentence'],
      ['-ing and -ed clauses', 'the man sitting …, the car stolen …'],
    ]),
    module('B', 'Adjectives and adverbs', [
      ['-ing and -ed adjectives', 'boring / bored'],
      ['Adjective order', 'a lovely old wooden table'],
      ['Adjectives after verbs', 'look tired, sound good'],
      ['Adjectives and adverbs', 'quick / quickly; good / well; hard / hardly'],
      ['so and such', "so tired, such a nice day"],
      ['enough and too', 'too hot to …, not warm enough'],
      ['quite, pretty, rather, fairly', 'degree'],
      ['Comparatives', 'much bigger, the sooner the better'],
      ['as … as', 'as soon as possible, twice as much'],
      ['Superlatives', 'the best I have ever …'],
      ['Adverbs and word order', 'place and time; frequency; still, yet, even'],
    ]),
    module('B', 'Linking words', [
      ['although, in spite of, despite', 'contrast'],
      ['as', 'as I walked …; as it was late'],
      ['like and as', 'like his father / as a teacher'],
      ['as if, as though', 'You look as if you …'],
      ['for, during, while', 'time'],
      ['by and until, by the time', 'deadlines'],
    ]),
    module('B', 'Prepositions', [
      ['at, on, in: time', 'on time / in time; at the end / in the end'],
      ['in, at, on: position', 'in the picture, at the party, on the bus'],
      ['to, at, in, into', 'arrive in / at, get into'],
      ['by', 'by car, by mistake, a book by …'],
      ['Noun + preposition', 'reason for, cause of, increase in'],
      ['Adjective + preposition', 'nice of you, angry with, proud of'],
      ['Verb + preposition', 'depend on, apologise for, accuse of'],
    ]),
    module('B', 'Phrasal verbs', [
      ['Phrasal verbs: in and out', 'fill in, drop out, find out'],
      ['Phrasal verbs: on and off', 'carry on, put off, turn down'],
      ['Phrasal verbs: up and down', 'give up, turn up, break down'],
      ['Phrasal verbs: away and back', 'give away, call back'],
    ]),
  ],
  C: [
    module('C', 'Tenses', [
      ['State verbs in continuous forms', "I'm thinking of …; she's being difficult"],
      ['Present perfect and past simple: nuances', 'news, recent past, time up to now'],
      ['Past perfect: uses', 'after, as soon as, by the time; I had hoped'],
      ['Future forms compared', 'will, going to, present continuous, future continuous'],
      ['be to, be about to', 'The president is to visit …; be on the verge of'],
      ['Future in the past', 'was going to, was to, would'],
      ['Future perfect continuous', 'By June I will have been working …'],
    ]),
    module('C', 'Modality', [
      ['will, would, used to: habits', 'She will keep interrupting; he would sit'],
      ['Possibility', 'may, might, could; may well, might as well'],
      ['Deduction in the past', 'must have, can\'t have, might have been'],
      ['Obligation and necessity', "need, needn't have / didn't need to, be supposed to"],
      ['should, ought to, had better', 'criticism: you should have …'],
      ['Semi-modals', 'be bound to, be likely to, be sure to'],
    ]),
    module('C', 'Passive and reporting', [
      ['Passive: advanced forms', 'being done, to have been done; get-passive'],
      ['Reporting verbs with the passive', 'He is thought to have left; It is believed that'],
      ['Reporting verb patterns', 'advise, insist, deny, accuse, admit'],
      ['Reported speech: no tense change', 'current truths, reporting now'],
      ['Reporting with modals', 'could, should, might in reported speech'],
    ]),
    module('C', 'Verb patterns', [
      ['Verb + -ing or infinitive: meaning', 'go on, mean, need, regret, try'],
      ['Verb + object + -ing or infinitive', 'I heard him leave / leaving'],
      ['Verbs + wh-clause', 'I wonder whether …; explain how'],
      ['Perfect and passive infinitives and -ing', 'to have done, being told, having been'],
    ]),
    module('C', 'Nouns and articles', [
      ['Compound nouns', 'noun + noun, noun + -ing, adjective + noun'],
      ['Countable and uncountable: shifts', 'a coffee, a knowledge of, experience'],
      ['Agreement', 'collective nouns, a number of / the number of, none of them is'],
      ['Articles: generic reference', 'The tiger is …; tigers; a tiger'],
      ['a / an and one', 'one day, a hundred, not one'],
      ['Zero article and the: special cases', 'by car, in bed, at dawn; the rich'],
    ]),
    module('C', 'Determiners and pronouns', [
      ['Quantifiers: advanced', 'few / a few / quite a few; many a …; the majority of'],
      ['each, every, all, whole', 'contrasts and agreement'],
      ['one, ones, that of', 'the one I want; those who'],
      ['Substitution: so, not, do so', 'I suppose so; if so; she did so'],
      ['Ellipsis', "I'd like to; she can, but I can't"],
    ]),
    module('C', 'Relative clauses', [
      ['Prepositions in relative clauses', 'the person to whom …; which formal and informal'],
      ['whose, what, whatever', 'what I need is …; whoever, wherever'],
      ['Infinitive relative clauses', 'the first person to arrive; nothing to do'],
      ['Participle relative clauses', 'the man standing …, the report written …'],
    ]),
    module('C', 'Adjectives and adverbs', [
      ['Gradable and non-gradable adjectives', 'very cold / absolutely freezing'],
      ['Adjective + that-clause or to-infinitive', "I'm sure that …; it's essential that"],
      ['Participle adjectives', 'well-known, long-lasting, broken-down'],
      ['Position of adverbs', 'focus adverbs: only, even, also'],
      ['Degree adverbs', 'quite, rather, fairly, somewhat, utterly'],
      ['Comparison: advanced', 'the more … the more; far / by far; nowhere near as'],
    ]),
    module('C', 'Adverbial clauses', [
      ['Time clauses', 'once, as soon as, no sooner … than'],
      ['Participle clauses', 'Having finished, …; Not knowing, …; with the door open'],
      ['Contrast', 'whereas, while, much as, even so'],
      ['Reason and result', 'as, since, seeing that; so … that, such … that'],
      ['Purpose', 'so as to, in order that, for fear of'],
    ]),
    module('C', 'Conditionals', [
      ['Mixed conditionals', 'If I had studied, I would be …'],
      ['if … will, if … should', 'If you\'ll wait; if you should see'],
      ['Alternatives to if', 'provided, supposing, otherwise, but for'],
      ['Inversion in conditionals', 'Had I known, Should you need, Were it not for'],
      ['wish, if only, would rather, it\'s time', 'unreal past forms'],
    ]),
    module('C', 'Emphasis and style', [
      ['Cleft sentences', "It was … that; What I need is …; All I did was"],
      ['Inversion after negative adverbials', 'Never have I …; Not only …; Hardly … when'],
      ['Fronting', 'Strange as it may seem, …; Into the room came …'],
      ['Emphatic do', 'I do like it; do sit down'],
      ['The subjunctive', 'I suggest he be; it is essential that she attend'],
      ['Linking adverbials', 'however, nevertheless, consequently, in contrast'],
      ['Hedging', 'it would seem, tend to, appear to, arguably'],
    ]),
    module('C', 'Prepositions and phrasal verbs', [
      ['Prepositions after nouns, adjectives and verbs', 'advanced collocations'],
      ['Three-part phrasal verbs', 'come up with, put up with, get away with'],
      ['Phrasal verbs: figurative meanings', 'bring about, play down, brush up on'],
    ]),
  ],
};
