import { module, type Syllabus } from './types';

/**
 * Испанский — программа Conquistador: три курса по Aragonés & Palencia,
 * «Gramática de uso del español» (SM), A1–A2, B1–B2 и C1–C2. Названия юнитов
 * и их порядок — как в книгах; подсказки — из тех же курсов.
 */
export const SPANISH: Syllabus = {
  A: [
    module('A', 'Sustantivo y artículo', [
      'Masculino, femenino (1)',
      'Masculino, femenino (2)',
      'Singular, plural',
      'Artículo indefinido',
      'Ausencia de artículo',
      'Artículo definido',
      'Contraste un / el',
      'Nombres propios',
      'Expresiones de tiempo',
      'Otros usos del artículo',
      'Omisión del nombre',
    ]),
    module('A', 'Demostrativos y adjetivos', [
      'Demostrativos',
      'Adjetivos calificativos',
      'Nacionalidad',
      'Comparativo y Superlativo (más / menos / el más)',
      'Comparativo (tan)',
    ]),
    module('A', 'Posesivos y números', [
      'Posesivos (1, átonos)',
      'Posesivos (2, tónicos)',
      'Cardinales (1)',
      'Cardinales (2)',
      'Cardinales (3)',
      'Ordinales',
    ]),
    module('A', 'Indefinidos y comparación', [
      'Todo',
      'Un / otro',
      'Mucho / poco / demasiado',
      'Alguien / algo / nadie / nada',
      'Más / menos / tanto (con nombres)',
    ]),
    module('A', 'Pronombres personales', [
      'Pronombres sujeto',
      'Objeto directo (OD)',
      'Objeto indirecto (OI)',
      'Se lo',
      'Contraste lo / la / le',
      'Reflexivos',
      'Con preposiciones',
    ]),
    module('A', 'Relativos e interrogativos', [
      'Que / donde',
      '¿Quién? / ¿Qué?',
      '¿Cuál? / ¿Qué?',
      '¿Dónde? / ¿Cuándo? / ¿Cuánto?',
      '¿Cómo? / ¿Por qué? / ¿Para qué?',
      '¡Qué! (exclamaciones)',
    ]),
    module('A', 'Ser / estar / tener / haber', [
      'Ser',
      'Estar',
      'Ser / estar',
      'Tener',
      'Hay (haber impersonal)',
      'Hay / estar',
    ]),
    module('A', 'Presente de indicativo', [
      'Presente -ar',
      'Presente -er',
      'Presente -ir',
      'Irregulares (1: e→ie / o→ue)',
      'Irregulares (2: duermo / juego)',
      'Otros usos del presente',
      'Pronominales (me / te / se)',
      'Contraste con / sin me',
      'Gustar',
      'Estar + gerundio',
      'Presente / estar+ger',
    ]),
    module('A', 'Pasados', [
      'Indefinido regular',
      'Indefinido irregular',
      'Perfecto (1)',
      'Perfecto (2)',
      'Perfecto / indefinido',
      'Imperfecto',
      'Indefinido / imperfecto',
    ]),
    module('A', 'Futuro', [
      'Futuro regular',
      'Futuro irregular',
      'Ir a + infinitivo',
      'Contraste formas de futuro',
    ]),
    module('A', 'Imperativo', [
      'Afirmativo regular',
      'Afirmativo irregular',
      'Negativo regular',
      'Negativo irregular',
      'Afirmativo: formas cortas',
      'Con se (lávate)',
      'Con pronombres',
    ]),
    module('A', 'Formas no personales', [
      'Infinitivo',
      'Expresiones con infinitivo (1)',
      'Expresiones (2: soler)',
      'Expresiones (3: acabar de)',
      'Gerundio',
      'Pronombres con infinitivo y gerundio',
      'Participio',
      'OD / OI (Quiero a Marta)',
    ]),
    module('A', 'Adverbios', [
      'Adverbios de lugar',
      'Adverbios de tiempo (1)',
      'Ya / todavía',
      'Frecuencia',
      'Cantidad (muy / mucho)',
      'Modo (-mente)',
      'Comparación de adverbios',
      'Negación (no / nunca)',
      'Coincidencia (yo sí / también)',
    ]),
    module('A', 'Conjunciones y preposiciones', [
      'Conjunciones (y / o / pero)',
      'Preposiciones (1: tiempo)',
      'Preposiciones (2: a / desde)',
      'Preposiciones (3: lugar)',
      'Preposiciones (4: a / de / en)',
      'Preposiciones (5: para / por)',
      'Verbos con preposición',
    ]),
    module('A', 'Oraciones subordinadas', [
      'Con que (creo que)',
      'Condicionales reales',
      'Temporales (cuando / antes de)',
      'Finales (para)',
      'Causales / consecutivas',
      'Impersonales (hace frío)',
    ]),
    module('A', 'Ortografía', [
      'Reglas de acentuación',
      'Uso de mayúsculas',
    ]),
  ],
  B: [
    module('B', 'Sustantivo y artículo', [
      ['Masculino, femenino (1)', 'Род названий людей: el hombre, la mujer'],
      ['Masculino, femenino (2)', 'Род предметов и слов'],
      ['Singular, plural', 'Множественное число: niño → niños'],
      ['Artículo indefinido', 'un, una, unos, unas'],
      ['Omisión del artículo', 'Es médico — без артикля'],
      ['Artículo definido', 'el, la, los, las'],
      ['Omisión del nombre · lo', 'la blanca, lo difícil'],
      ['Indefinido vs definido', 'un libro / el libro'],
      ['Artículo con nombres propios', 'la señorita Moreno, los Andes'],
      ['Artículo: tiempo y cantidad', 'el cinco de octubre'],
      ['Otros usos del definido', 'jugar al tenis, el español'],
    ]),
    module('B', 'Demostrativos y adjetivos', [
      ['Demostrativos', 'este, ese, aquel'],
      ['Adjetivos: género y número', 'inteligente, enfermo, español'],
      ['Colocación del adjetivo', 'un niño pobre / un pobre niño'],
      ['Comparativo y superlativo', 'más alto, el más alto'],
      ['Comparativo de igualdad', 'tan alto, igual de alto'],
      ['Comparación con nombres', 'más, menos, tanto (с существительными)'],
    ]),
    module('B', 'Posesivos e indefinidos', [
      ['Posesivos (1)', 'mi, tu, su, nuestro…'],
      ['Posesivos (2)', 'mío, tuyo, suyo…'],
      ['Indefinidos (1)', 'todos, algunos, varios, ninguno'],
      ['Indefinidos (2)', 'uno, otro'],
      ['Indefinidos (3)', 'cada, cualquiera'],
      ['Indefinidos (4)', 'alguien, algo, nadie, nada'],
      ['Numerales (1): ordinales', 'primero, undécimo…'],
      ['Numerales (2): fracciones', 'la mitad, el doble'],
    ]),
    module('B', 'Pronombres personales', [
      ['Sujeto y con preposición', 'yo, para mí, conmigo'],
      ['Pronombres de objeto (1)', 'me ama, me ha regalado'],
      ['Pronombres de objeto (2)', 'La comida la pago yo · se lo'],
      ['Reflexivos y recíprocos', 'me baño, nos queremos'],
      ['Pron. con imperativo/inf./ger.', 'dámelo, verte, diciéndolo'],
    ]),
    module('B', 'Relativos e interrogativos', [
      ['Relativos (1)', 'que, el que, quien'],
      ['Relativos (2)', 'donde, cuando, como'],
      ['Interrogativos (1)', '¿quién?, ¿qué?, ¿cuál?'],
      ['Contraste interrogativos', '¿qué? / ¿cuál?'],
      ['Interrogativos (2)', '¿dónde?, ¿cuándo?, ¿cuánto?'],
      ['Exclamativos', '¡qué!, ¡cuánto!, ¡cómo!'],
    ]),
    module('B', 'Presente de indicativo', [
      ['Ser y estar', 'soy, estoy'],
      ['Haber impersonal y estar', 'hay / está'],
      ['Presente: verbos regulares', 'trabajo, como, vivo'],
      ['Irregulares (1): cambio vocálico', 'quiero, mido, sueño'],
      ['Irregulares (2): yo irregular', 'voy, hago, conozco'],
      ['Irregulares (3): completamente irregulares', 'soy, voy, estoy, doy'],
      ['Otros usos del presente', '¿Qué haces el domingo?'],
      ['Presente: periodos de tiempo', 'Vivo aquí desde 1998'],
      ['Llevar para duración', 'Llevan siete meses casados'],
      ['Verbos con me, te, se…', 'Me aburro (pronominales)'],
      ['Verbos tipo gustar', 'Me gusta la ópera'],
      ['Estar + gerundio', 'Están jugando en el jardín'],
    ]),
    module('B', 'Pasados', [
      ['Indefinido: regulares', 'De joven, viví en México'],
      ['Indefinido: irregulares', 'Murió en 1616'],
      ['Pretérito perfecto', 'He tenido un accidente'],
      ['Perfecto vs indefinido', 'ha llamado / llamó'],
      ['Pretérito imperfecto', 'Quería ser astronauta'],
      ['Indefinido vs imperfecto', 'monté / montaba'],
      ['Estaba + gerundio', 'estaba trabajando / trabajé'],
      ['Pluscuamperfecto', 'había trabajado'],
    ]),
    module('B', 'Futuro y condicional', [
      ['Futuro simple', 'trabajaré, podré, haré'],
      ['Futuro vs ir a + inf.', 'voy a trabajar / trabajaré'],
      ['Contraste de formas de futuro', 'haré / voy a hacer / hago'],
      ['Futuro perfecto', 'habré trabajado'],
      ['Condicional simple', 'trabajaría, comería'],
      ['Condicional: irregulares', 'habría, podría, haría'],
      ['Condicional compuesto', 'habría trabajado'],
      ['Certeza y probabilidad', 'Serán las tres'],
    ]),
    module('B', 'Imperativo', [
      ['Imperativo: regulares', 'come, no comas'],
      ['Imperativo: irregulares (1)', 'cierra, pide'],
      ['Imperativo: irregulares (2)', 'sueña, duerme'],
      ['Imperativo: irregulares (3)', 'di, haz, pon, ven, sal'],
      ['Imperativo con pronombres', 'dámelo, no me lo des'],
    ]),
    module('B', 'Subjuntivo: formas', [
      ['Presente subj.: regulares', 'trabaje, coma, viva'],
      ['Presente subj.: irregulares (1)', 'quiera, pida'],
      ['Presente subj.: irregulares (2)', 'busque, juegue, empiece'],
      ['Presente subj.: irregulares (3)', 'conozca, diga, vaya'],
      ['Imperfecto subj.: regulares', 'trabajara, comiera'],
      ['Imperfecto subj.: irregulares', 'fuera, tuviera'],
      ['Pretérito perfecto subj.', 'haya trabajado'],
      ['Pluscuamperfecto subj.', 'hubiera trabajado'],
    ]),
    module('B', 'Subjuntivo: usos', [
      ['Expresar deseos', 'Quiero que me ayudes'],
      ['Expresar probabilidad (1)', 'Quizá lo haga'],
      ['Expresar probabilidad (2)', 'A lo mejor me toca'],
      ['Emociones y sentimientos', 'Me alegro de que…'],
      ['Valoraciones', 'Me parece bien que estudies'],
      ['Indicativo vs subjuntivo', 'Creo que es / No creo que sea'],
    ]),
    module('B', 'Estilo indirecto', [
      ['Estilo indirecto (1)', 'Dice que… / Dijo que…'],
      ['Estilo indirecto (2)', 'Me preguntó dónde vivía'],
      ['Estilo indirecto (3)', 'Me pidió que la ayudara'],
    ]),
    module('B', 'Infinitivo, gerundio, participio', [
      ['Infinitivo', 'Trabajar es…'],
      ['Verbos seguidos de infinitivo', 'Sueño con ser famoso'],
      ['Infinitivo o subjuntivo', 'Quiero ir / Quiero que vayas'],
      ['Pronombres con el infinitivo', 'hacerlo, aburrirse'],
      ['Expresiones con infinitivo (1)', 'ir a, acabar de, volver a'],
      ['Expresiones con infinitivo (2)', 'tener que, hay que, poder'],
      ['Expresiones con infinitivo (3)', 'soler, llevar sin'],
      ['Gerundio', 'paseando por el parque'],
      ['Expresiones con gerundio', 'seguir, llevar + gerundio'],
      ['Participio', 'trabajado, abierto, dicho'],
    ]),
    module('B', 'Adverbios y preposiciones', [
      ['Grados de cualidad/cantidad', 'muy, mucho, muchísimo'],
      ['Adverbios en -mente', 'fácilmente, rápidamente'],
      ['Preposiciones (1)', 'a, de, en, desde, hasta'],
      ['Preposiciones (2)', 'entre, sobre, con, sin, según'],
      ['Por y para', 'preposiciones (3)'],
      ['Verbos con preposición', 'Acuérdate de mí'],
    ]),
    module('B', 'Oraciones subordinadas', [
      ['Oraciones de relativo', 'La corbata que me regalaste'],
      ['Temporales (1)', 'antes de (que), después de (que)'],
      ['Temporales (2)', 'cuando, en cuanto…'],
      ['Lugar y modo', 'donde, como'],
      ['Causales', 'porque, como, puesto que'],
      ['Finales', 'para (que)'],
      ['Condicionales (1): reales', 'Si apruebo, podré ir'],
      ['Condicionales (2): irreales presente', 'Si encontrara trabajo, me casaría'],
      ['Condicionales (3): irreales pasado', 'Si hubiera…, habría…'],
      ['Consecutivas', 'tan… que, tanto que'],
      ['Concesivas', 'aunque, a pesar de que'],
    ]),
    module('B', 'Pasiva, impersonalidad, acentos', [
      ['Impersonales (1): se', 'Aquí se vive muy bien'],
      ['Impersonales (2)', 'Llueve, hace frío, hay'],
      ['Voz pasiva', 'fue encontrado, se compran'],
      ['Reglas de acentuación', 'adiós, león, continúa'],
    ]),
  ],
  C: [
    module('C', 'Sustantivo y artículo', [
      ['Masculino / femenino', 'el capital / la capital — род меняет значение'],
      ['Singular / plural', 'carnés, líderes, airbags — множественное заимствований'],
      ['Artículos: uso y omisión', 'El Presidente está preocupado. La han hecho directora'],
      ['Artículos con nombres propios', 'un Picasso, el Madrid de los Austrias'],
      ['Indefinido intensificador', 'una santa, un frío — усиление через un/una'],
      ['Definido y lo intensificadores', '¡El frío que hacía! ¡Lo mal que conduce!'],
    ]),
    module('C', 'Adjetivos y demostrativos', [
      ['Demostrativos (1)', 'este, ese, aquel… — пространство, время, контекст'],
      ['Demostrativos (2)', '¡esta Ana!, el tío este — оценка и эмоция'],
      ['El adjetivo', 'casas altas / altos rascacielos — позиция меняет смысл'],
      ['El adjetivo con verbos', 'Parece antigua. Vivo tranquilo'],
      ['Modificación de adjetivos', 'nada de gracioso, de lo más divertido'],
      ['Modificación de nombres', 'todo mojada, mucha moto'],
    ]),
    module('C', 'Posesivos y pronombres', [
      ['Posesivos', 'mi, mío, lo mío — от принадлежности до идиом'],
      ['Cuantificadores', 'todos, cada, sendos'],
      ['Pronombres de sujeto', 'él mismo, ello — когда местоимение обязательно'],
      ['Objeto directo', 'A esta chica la conozco. No se le ve muy bien'],
      ['Objeto indirecto', 'No te nos escondas. Nos cayó encima'],
      ['Usos de me, te, se', 'Se han hecho un chalé. Me bebí un café'],
      ['Pronombres con preposición', 'para sí, consigo'],
    ]),
    module('C', 'Construcciones con se', [
      ['Se impersonal', 'Aquí se come bien. Se esperaba que lloviera'],
      ['Otras construcciones con se', 'Se acusó a los detenidos. Se necesitan extras'],
    ]),
    module('C', 'Relativos e interrogativos', [
      ['Relativos (1)', 'la mujer que, la chica con (la) que'],
      ['Relativos (2)', 'La mujer, que había llamado antes,…'],
      ['Relativos (3)', 'la chica cuyo hermano, cuantos pasteles'],
      ['Interrogativos (1)', '¿Quién…? ¿Cuál…? ¿Qué…?'],
      ['Interrogativos (2)', '¿Qué demonios…? ¿Cómo es que…?'],
      ['Exclamativos (1)', '¡Quién fuera más joven! ¡Vaya casa!'],
      ['Exclamativos (2)', '¡Qué de niños! ¡Cuánta gente!'],
      ['Exclamativos (3)', '¡Cómo come! ¡Por dónde nos llevan!'],
    ]),
    module('C', 'Adverbios, ser y estar', [
      ['Adverbios en -mente (1)', 'instintivamente, sigilosamente'],
      ['Adverbios en -mente (2)', 'locamente enamorados, cuidadosamente tallada'],
      ['Ser y estar', 'Soy soltera / Estoy soltera'],
    ]),
    module('C', 'Presente y duración', [
      ['Presente: presente y futuro', 'El sol sale por el Este. Hablamos mañana'],
      ['Presente histórico', 'Recibe el Premio Nobel en 1971'],
      ['Presente: otros usos', '¿Salimos esta noche?'],
      ['Presente: duración', 'Hace mucho que no como tacos'],
      ['Llevar para duración', 'Llevamos tres semanas en Japón'],
      ['Estar + gerundio', 'Le estamos cuidando los gatos a Clara'],
    ]),
    module('C', 'Pasados', [
      ['Pretérito imperfecto', 'Cuando estudiaba. Mientras dormíamos'],
      ['Pretérito indefinido', 'Anoche vi a Sofía'],
      ['Imperfecto / indefinido', 'Se cayó del caballo mientras practicaba'],
      ['Contraste de pasados', 'hice / hacía / he hecho / estaba haciendo'],
      ['Pluscuamperfecto', 'Se había gastado todo el dinero'],
      ['Duración en el pasado', 'Hacía dos años que conocía a Sonia…'],
    ]),
    module('C', 'Futuro y condicional', [
      ['Futuro simple (1)', 'Nevará en el Norte'],
      ['Futuro simple (2)', '¡Será egoísta! ¡Tú verás!'],
      ['Futuro compuesto', 'En diciembre ya habrá nacido el niño'],
      ['Futuro simple / compuesto', 'acabaré / habré acabado'],
      ['Condicional simple', 'Estaría en el jardín'],
      ['Condicional compuesto', 'habría estudiado'],
      ['Simple / compuesto', 'iría / habría ido'],
    ]),
    module('C', 'Imperativo', [
      ['Imperativo (1)', 'Haz eso y verás'],
      ['Imperativo (2)', 'Pensemos, no nos precipitemos'],
      ['Imperativo (3)', 'Mira. Oye — маркеры дискурса'],
      ['Imperativo (4)', '¡Anda! ¡Venga! ¡Vamos!'],
      ['Imperativo (5)', '¡Vaya! ¡Fíjate! ¡Toma! ¡Dale!'],
    ]),
    module('C', 'Subjuntivo: presente', [
      ['Presente de subjuntivo (1)', '¡Ojalá estén en casa! ¡Que tengas buen viaje!'],
      ['Presente de subjuntivo (2)', 'Necesito que me ayudes'],
      ['Presente de subjuntivo (3)', '¿Te molesta que fume?'],
      ['Presente de subjuntivo (4)', 'Es una lástima que dejes de trabajar'],
      ['Indicativo o subjuntivo (1)', 'Creo que hay / No creo que haya'],
    ]),
    module('C', 'Subjuntivo: otros tiempos', [
      ['Imperfecto de subjuntivo (1)', '¡Qué más quisiera!'],
      ['Imperfecto de subjuntivo (2)', 'Quería que me ayudaras'],
      ['Indicativo o subjuntivo (2)', 'Pensé que estabas / No pensé que estuvieras'],
      ['Perfecto de subjuntivo (1)', '¡Ojalá hayan regresado!'],
      ['Perfecto de subjuntivo (2)', 'Es imposible que lo haya hecho él'],
      ['Indicativo o subjuntivo (3)', 'Creo que han tenido / No creo que hayan tenido'],
      ['Pluscuamperfecto de subjuntivo', '¡Ojalá hubiera ganado!'],
      ['Indicativo o subjuntivo (4)', 'Creo que habían tenido / No creo que hubieran tenido'],
      ['Subjuntivo: indeterminación', 'Cuando quieras. Alguien que hable español'],
    ]),
    module('C', 'Infinitivo', [
      ['El infinitivo', 'descansar, haber descansado'],
      ['Infinitivo o subjuntivo', 'Nos complace invitarlos. Es fácil ganar'],
      ['Verbos + infinitivo o subjuntivo', 'Merecieron ganar. Mereces que te dé…'],
      ['Infinitivo, indicativo o subjuntivo', 'Creo tener razón / Creo que tengo razón'],
      ['Infinitivo con preposiciones', 'sin querer, difícil de creer'],
      ['Verbos con preposición', 'Se niega a obedecer'],
      ['Expresiones con infinitivo (1)', 'Rompió a llorar. Llegué a tomarle cariño'],
      ['Expresiones con infinitivo (2)', 'Tuve que ir. Hay que darse prisa'],
    ]),
    module('C', 'Participio y gerundio', [
      ['Participio (1)', '¿sorprendida?, siempre cansado'],
      ['Participio (2)', 'Llega agotada. Tengo ahorrados mil euros'],
      ['Gerundio (1)', '¡Siempre trabajando!'],
      ['Gerundio (2)', 'He estado limpiando. Iba conduciendo'],
    ]),
    module('C', 'Relativas y temporales', [
      ['Oraciones de relativo especificativas', 'la fruta que compré, lo que yo quiero'],
      ['Oraciones de relativo explicativas', 'mi padre, que está de vacaciones...'],
      ['Oraciones temporales (1)', 'antes de que me lo preguntes'],
      ['Oraciones temporales (2)', 'cuando llueve, en cuanto oye el timbre'],
      ['Oraciones de lugar y modo', 'donde no haya, como cocinaba su madre'],
    ]),
    module('C', 'Causales, consecutivas, finales', [
      ['Oraciones causales (1)', 'Porque me ha mentido. Es que no me gusta.'],
      ['Oraciones causales (2)', 'gracias a vosotros, de tantos libros como tiene'],
      ['Oraciones consecutivas (1)', 'Así que cállate. De ahí que regresara.'],
      ['Oraciones consecutivas (2)', 'de un modo que parece, tal enfado que no quiere'],
      ['Oraciones consecutivas (3)', 'un frío que no se puede, de un orgulloso que resulta'],
      ['Oraciones finales', 'para comprarme, con idea de pasar, a tratar'],
    ]),
    module('C', 'Condicionales y concesivas', [
      ['Oraciones condicionales (1)', 'Si nieva, habrá mucha agua'],
      ['Oraciones condicionales (2)', 'como pierda el trabajo, de ser así'],
      ['Oraciones condicionales (3)', 'Si tuviera dinero, te invitaría'],
      ['Oraciones condicionales (4)', 'Si hubieras trabajado, no tendrías problemas'],
      ['Oraciones condicionales (5)', 'siempre que, a menos que'],
      ['Oraciones concesivas (1)', 'aunque no están de acuerdo, a pesar del calor'],
      ['Oraciones concesivas (2)', 'por fuerte que parezca, si bien hay mucha nieve'],
      ['Oraciones concesivas (3)', 'con lo lista que es, digas lo que digas'],
    ]),
    module('C', 'Comparativas y estilo indirecto', [
      ['Oraciones comparativas (1)', 'más guapo que inteligente, menos de lo que creía'],
      ['Oraciones comparativas (2)', 'más años que Matusalén, menos frío de lo que pensaba'],
      ['Estilo indirecto (1)', 'Dice que llegará tarde. / Dijo que llegaría tarde.'],
      ['Estilo indirecto (2)', 'Me han preguntado en qué países he trabajado'],
      ['Estilo indirecto (3)', 'Ha dicho que recojamos. Os dije que recogierais.'],
    ]),
  ],
};
