import { locale, t, type UiLocale } from './i18n';
import type { LanguageCode } from './types';

export interface Topic {
  id: string;
  /** Название на изучаемом языке — его же увидит собеседник. */
  label: string;
  /**
   * Ролевая ситуация: партнёр играет сотрудника, а не расспрашивает о
   * впечатлениях. Фразовые глаголы — темы «Слов» английского по базовому
   * глаголу, тренажёры — темы «Слов» с упражнениями на трудную грамматику.
   * Обычным темам поле не нужно.
   */
  kind?: 'roleplay' | 'phrasal' | 'drill';
}

/**
 * Описание сцены для ролевых тем — по одному на идентификатор, а не на язык:
 * роль партнёра одна и та же, меняется только язык разговора.
 */
export const ROLEPLAY_SCENES: Record<string, string> = {
  bank: [
    'You are a clerk at a bank counter and the learner is the customer in front of you.',
    'They have come in with something to sort out: opening an account, a card that stopped working, a transfer that did not arrive, a fee they do not understand.',
    'Ask what they need, then handle it as a real clerk would — ask for the details, explain the options, the paperwork and the waiting times.',
  ].join(' '),
  pharmacy: [
    'You are a pharmacist behind the counter and the learner is the customer.',
    'They are describing a complaint or asking for a particular medicine.',
    'Ask what the symptoms are, how long they have lasted, what they have already taken and whether they have a prescription, then offer what you can sell them and explain how to take it.',
  ].join(' '),
  clinic: [
    'You are a doctor at a health centre and the learner is your patient, in with a cold or the flu.',
    'Ask what is wrong, how long it has lasted, about fever, cough, sore throat and headache, what they have already taken and whether they have any allergies.',
    'Then say what you think it is, what to take and for how long, and whether they need a sick note or should come back.',
  ].join(' '),
  repair: [
    'You are an agent at a repair service for household appliances and the learner is calling you.',
    'Something has broken: a fridge, a washing machine, an oven, a dishwasher.',
    'Ask which appliance it is, the make and model, what exactly it does wrong, how old it is and whether it is still under warranty, then offer a visit time and a rough price for the call-out.',
  ].join(' '),
  office: [
    'You are a friendly colleague of the learner in an office where the atmosphere is relaxed and supportive, and you are chatting at your desks.',
    'Talk about the working day the way colleagues do: current tasks and deadlines, an email from a client that needs an answer, getting ready for a meeting, a client call that went well or badly.',
    'Now and then ask the learner to help you word a short polite message to a client or to rehearse what to say on a call, and react to it as a colleague would. Keep the tone warm and informal, with a light joke here and there.',
  ].join(' '),
  tax: [
    'You are an official at the tax office of the country where the language of this conversation is mainly spoken: for English the United Kingdom (HMRC), German — Germany (Finanzamt), French — France (centre des impôts), Spanish — Spain (Agencia Tributaria), Italian — Italy (Agenzia delle Entrate), European Portuguese — Portugal (Finanças), Brazilian Portuguese — Brazil (Receita Federal), Ukrainian — Ukraine (податкова служба), Dutch — the Netherlands (Belastingdienst), Polish — Poland (urząd skarbowy), Romanian — Romania (ANAF), Czech — the Czech Republic (finanční úřad). The learner is a resident who has come with a question.',
    'Typical questions: getting a tax number, registering as self-employed, the annual income tax return and its deadline, VAT, deductions and allowances, a letter from the tax office they did not understand, a payment or a fine.',
    'Use the real terms of that country\'s system and explain them simply at the learner\'s level, ask for the details you need and say what to do next. Do not state exact current rates or thresholds as fact — say they should check them on the official website.',
  ].join(' '),
  dentist: [
    'You are a dentist and the learner is your patient in the chair.',
    'Ask what brings them in — toothache, a broken filling, bleeding gums, a check-up or cleaning — where it hurts, since when, and whether hot, cold or sweet makes it worse.',
    'Explain what you see and what you suggest — a filling, a clean, an X-ray, a root canal, an extraction — whether it will hurt, how long it takes, what it costs or what insurance covers, and what to do and avoid afterwards.',
  ].join(' '),
  familydoctor: [
    'You are the learner\'s family doctor (general practitioner) at a routine appointment.',
    'They have come about something ongoing rather than an emergency: tiredness, back pain, blood pressure, sleep, a repeat prescription, a referral to a specialist or a sick note for work.',
    'Ask about their symptoms, lifestyle and medicines, explain what you think, order tests if needed and agree on the next steps and a follow-up appointment.',
  ].join(' '),
  pediatrician: [
    'You are a paediatrician and the learner is a parent who has brought their child to you.',
    'The child has a fever, a cough, a rash or an upset stomach, or is due for a check-up or a vaccination.',
    'Ask the parent about the child\'s age, symptoms, temperature, appetite, sleep and vaccinations, explain what it is likely to be, what to give and in what dose, which warning signs mean they should come back at once, and whether the child can go to nursery or school.',
  ].join(' '),
  lab: [
    'You are a receptionist and nurse at a medical laboratory and the learner has come for tests.',
    'They may have a referral for a blood or urine test, want to book a test themselves, or have come to collect and understand their results.',
    'Ask for the referral and their details, check whether they have fasted, explain how the test is done and when and how the results will be ready, and explain simply what the main values in a result mean — while making clear that the doctor will interpret them.',
  ].join(' '),
  jobinterview: [
    'You are an interviewer at a company — friendly but professional — and the learner has applied for a job with you.',
    'Ask them to introduce themselves, then about their experience, skills and languages, why they want this job, when they could start and, if it comes up naturally, their salary expectations. Answer their questions about the job, the hours and the team.',
    'Keep it one question at a time, react to their answers as a real interviewer would and, at the end, say what the next step is and when they will hear from you.',
  ].join(' '),
  schoolenrol: [
    'You are the secretary at a school and the learner is a parent, new in the country, who has come to enrol their child.',
    'Ask about the child — name, age, the school and year they came from, languages they speak — and explain which documents you need, such as a birth certificate, a vaccination record and proof of address.',
    'Explain the practical side: which class the child goes into, extra language support if they need it, the timetable, lunch, after-school care, what to bring on the first day. Answer the parent\'s questions patiently.',
  ].join(' '),
  immigration: [
    'You are an official at the immigration office of the country where the language of this conversation is mainly spoken: for English the United Kingdom (UK Visas and Immigration), German — Germany (Ausländerbehörde), French — France (préfecture), Spanish — Spain (Oficina de Extranjería), Italian — Italy (Questura), European Portuguese — Portugal (AIMA), Brazilian Portuguese — Brazil (Polícia Federal), Ukrainian — Ukraine (Державна міграційна служба), Dutch — the Netherlands (IND), Polish — Poland (urząd wojewódzki), Romanian — Romania (Inspectoratul General pentru Imigrări), Czech — the Czech Republic (the Ministry of the Interior\'s department for foreigners, OAMP).',
    'The learner has come about their residence permit: applying for the first time, renewing it, changing their status, registering their address, or a letter they did not understand.',
    'Ask for the details and documents you need, explain the steps, appointments, fingerprints and photos and roughly how long it takes, calmly and clearly at the learner\'s level. Do not state exact fees, rules or deadlines as fact — say they should check the official website.',
  ].join(' '),
};

/**
 * Шаблоны разговора на случай, когда своей темы нет. По тридцать четыре на
 * язык: тридцать три общих (с 2026-09-28 — и промышленность, IT, ИИ, экология)
 * и одна своя для каждого языка, плюс тринадцать ролевых сцен — банк, аптека,
 * врач, ремонт, офис, налоговая, стоматолог, семейный врач, педиатр,
 * лаборатория, собеседование, запись ребёнка в школу, миграционная служба.
 *
 * Тема уходит в system prompt, а первую реплику партнёр придумывает сам под
 * уровень — готовые фразы пришлось бы писать отдельно для A1 и для C1.
 */
export const TOPICS: Record<LanguageCode, Topic[]> = {
  en: [
    { id: 'routine', label: 'Daily routine' },
    { id: 'food', label: 'Food and cooking' },
    { id: 'travel', label: 'Travel and holidays' },
    { id: 'work', label: 'Work and career' },
    { id: 'family', label: 'Family' },
    { id: 'friendship', label: 'Friendship' },
    { id: 'city', label: 'City life' },
    { id: 'sport', label: 'Sport and fitness' },
    { id: 'music', label: 'Music' },
    { id: 'films', label: 'Films and series' },
    { id: 'books', label: 'Books and reading' },
    { id: 'weather', label: 'Weather and seasons' },
    { id: 'shopping', label: 'Shopping' },
    { id: 'health', label: 'Health and doctors' },
    { id: 'tech', label: 'Technology and gadgets' },
    { id: 'money', label: 'Money and prices' },
    { id: 'school', label: 'School and university' },
    { id: 'childhood', label: 'Childhood memories' },
    { id: 'future', label: 'Plans for the future' },
    { id: 'holidays', label: 'Holidays and traditions' },
    { id: 'nature', label: 'Nature and animals' },
    { id: 'transport', label: 'Transport and traffic' },
    { id: 'home', label: 'Home and repairs' },
    { id: 'restaurants', label: 'Restaurants and cafés' },
    { id: 'hobbies', label: 'Hobbies' },
    { id: 'news', label: 'News and current events' },
    { id: 'history', label: 'History' },
    { id: 'art', label: 'Art and museums' },
    { id: 'languages', label: 'Learning languages' },
    { id: 'industry', label: 'Industry and manufacturing' },
    { id: 'infotech', label: 'IT and software' },
    { id: 'ai', label: 'Artificial intelligence' },
    { id: 'ecology', label: 'Ecology and climate' },
    { id: 'local-en', label: 'British and American English' },
    { id: 'bank', label: 'At the bank', kind: 'roleplay' },
    { id: 'pharmacy', label: 'At the pharmacy', kind: 'roleplay' },
    { id: 'clinic', label: "At the doctor's with a cold", kind: 'roleplay' },
    { id: 'repair', label: 'Calling an appliance repair service', kind: 'roleplay' },
    { id: 'office', label: 'A day at the office', kind: 'roleplay' },
    { id: 'tax', label: 'At the tax office', kind: 'roleplay' },
    { id: 'dentist', label: 'At the dentist', kind: 'roleplay' },
    { id: 'familydoctor', label: 'At the family doctor', kind: 'roleplay' },
    { id: 'pediatrician', label: 'At the paediatrician', kind: 'roleplay' },
    { id: 'lab', label: 'At the medical laboratory', kind: 'roleplay' },
    { id: 'jobinterview', label: 'A job interview', kind: 'roleplay' },
    { id: 'schoolenrol', label: 'Enrolling a child at school', kind: 'roleplay' },
    { id: 'immigration', label: 'At the immigration office', kind: 'roleplay' },
  ],

  de: [
    { id: 'routine', label: 'Tagesablauf' },
    { id: 'food', label: 'Essen und Kochen' },
    { id: 'travel', label: 'Reisen und Urlaub' },
    { id: 'work', label: 'Arbeit und Beruf' },
    { id: 'family', label: 'Familie' },
    { id: 'friendship', label: 'Freundschaft' },
    { id: 'city', label: 'Leben in der Stadt' },
    { id: 'sport', label: 'Sport und Fitness' },
    { id: 'music', label: 'Musik' },
    { id: 'films', label: 'Filme und Serien' },
    { id: 'books', label: 'Bücher und Lesen' },
    { id: 'weather', label: 'Wetter und Jahreszeiten' },
    { id: 'shopping', label: 'Einkaufen' },
    { id: 'health', label: 'Gesundheit und Ärzte' },
    { id: 'tech', label: 'Technik und Geräte' },
    { id: 'money', label: 'Geld und Preise' },
    { id: 'school', label: 'Schule und Universität' },
    { id: 'childhood', label: 'Kindheitserinnerungen' },
    { id: 'future', label: 'Zukunftspläne' },
    { id: 'holidays', label: 'Feste und Traditionen' },
    { id: 'nature', label: 'Natur und Tiere' },
    { id: 'transport', label: 'Verkehr und Bahn' },
    { id: 'home', label: 'Wohnen und Renovieren' },
    { id: 'restaurants', label: 'Restaurants und Cafés' },
    { id: 'hobbies', label: 'Hobbys' },
    { id: 'news', label: 'Nachrichten und Politik' },
    { id: 'history', label: 'Geschichte' },
    { id: 'art', label: 'Kunst und Museen' },
    { id: 'languages', label: 'Sprachen lernen' },
    { id: 'industry', label: 'Industrie und Produktion' },
    { id: 'infotech', label: 'IT und Software' },
    { id: 'ai', label: 'Künstliche Intelligenz' },
    { id: 'ecology', label: 'Ökologie und Klima' },
    { id: 'local-de', label: 'Weihnachtsmärkte und Oktoberfest' },
    { id: 'bank', label: 'Auf der Bank', kind: 'roleplay' },
    { id: 'pharmacy', label: 'In der Apotheke', kind: 'roleplay' },
    { id: 'clinic', label: 'Beim Arzt mit einer Erkältung', kind: 'roleplay' },
    { id: 'repair', label: 'Anruf beim Reparaturdienst', kind: 'roleplay' },
    { id: 'office', label: 'Im Büro', kind: 'roleplay' },
    { id: 'tax', label: 'Beim Finanzamt', kind: 'roleplay' },
    { id: 'dentist', label: 'Beim Zahnarzt', kind: 'roleplay' },
    { id: 'familydoctor', label: 'Beim Hausarzt', kind: 'roleplay' },
    { id: 'pediatrician', label: 'Beim Kinderarzt', kind: 'roleplay' },
    { id: 'lab', label: 'Im medizinischen Labor', kind: 'roleplay' },
    { id: 'jobinterview', label: 'Im Vorstellungsgespräch', kind: 'roleplay' },
    { id: 'schoolenrol', label: 'Das Kind in der Schule anmelden', kind: 'roleplay' },
    { id: 'immigration', label: 'Bei der Ausländerbehörde', kind: 'roleplay' },
  ],

  fr: [
    { id: 'routine', label: 'La journée type' },
    { id: 'food', label: 'La cuisine et les repas' },
    { id: 'travel', label: 'Les voyages et les vacances' },
    { id: 'work', label: 'Le travail et la carrière' },
    { id: 'family', label: 'La famille' },
    { id: 'friendship', label: "L'amitié" },
    { id: 'city', label: 'La vie en ville' },
    { id: 'sport', label: 'Le sport' },
    { id: 'music', label: 'La musique' },
    { id: 'films', label: 'Les films et les séries' },
    { id: 'books', label: 'Les livres et la lecture' },
    { id: 'weather', label: 'Le temps et les saisons' },
    { id: 'shopping', label: 'Les courses et les achats' },
    { id: 'health', label: 'La santé et les médecins' },
    { id: 'tech', label: 'La technologie' },
    { id: 'money', label: "L'argent et les prix" },
    { id: 'school', label: "L'école et l'université" },
    { id: 'childhood', label: "Les souvenirs d'enfance" },
    { id: 'future', label: "Les projets d'avenir" },
    { id: 'holidays', label: 'Les fêtes et les traditions' },
    { id: 'nature', label: 'La nature et les animaux' },
    { id: 'transport', label: 'Les transports' },
    { id: 'home', label: 'Le logement et les travaux' },
    { id: 'restaurants', label: 'Les restaurants et les cafés' },
    { id: 'hobbies', label: 'Les loisirs' },
    { id: 'news', label: "L'actualité" },
    { id: 'history', label: "L'histoire" },
    { id: 'art', label: "L'art et les musées" },
    { id: 'languages', label: "L'apprentissage des langues" },
    { id: 'industry', label: "L'industrie" },
    { id: 'infotech', label: "L'informatique" },
    { id: 'ai', label: "L'intelligence artificielle" },
    { id: 'ecology', label: "L'écologie et le climat" },
    { id: 'local-fr', label: 'Le fromage et le vin' },
    { id: 'bank', label: 'À la banque', kind: 'roleplay' },
    { id: 'pharmacy', label: 'À la pharmacie', kind: 'roleplay' },
    { id: 'clinic', label: 'Chez le médecin avec un rhume', kind: 'roleplay' },
    { id: 'repair', label: 'Appel au service de réparation', kind: 'roleplay' },
    { id: 'office', label: 'Au bureau', kind: 'roleplay' },
    { id: 'tax', label: 'Au centre des impôts', kind: 'roleplay' },
    { id: 'dentist', label: 'Chez le dentiste', kind: 'roleplay' },
    { id: 'familydoctor', label: 'Chez le médecin traitant', kind: 'roleplay' },
    { id: 'pediatrician', label: 'Chez le pédiatre', kind: 'roleplay' },
    { id: 'lab', label: "Au laboratoire d'analyses", kind: 'roleplay' },
    { id: 'jobinterview', label: "L'entretien d'embauche", kind: 'roleplay' },
    { id: 'schoolenrol', label: "L'inscription d'un enfant à l'école", kind: 'roleplay' },
    { id: 'immigration', label: 'À la préfecture', kind: 'roleplay' },
  ],

  es: [
    { id: 'routine', label: 'La rutina diaria' },
    { id: 'food', label: 'La comida y la cocina' },
    { id: 'travel', label: 'Los viajes y las vacaciones' },
    { id: 'work', label: 'El trabajo y la carrera' },
    { id: 'family', label: 'La familia' },
    { id: 'friendship', label: 'La amistad' },
    { id: 'city', label: 'La vida en la ciudad' },
    { id: 'sport', label: 'El deporte' },
    { id: 'music', label: 'La música' },
    { id: 'films', label: 'Las películas y las series' },
    { id: 'books', label: 'Los libros y la lectura' },
    { id: 'weather', label: 'El tiempo y las estaciones' },
    { id: 'shopping', label: 'Las compras' },
    { id: 'health', label: 'La salud y los médicos' },
    { id: 'tech', label: 'La tecnología' },
    { id: 'money', label: 'El dinero y los precios' },
    { id: 'school', label: 'La escuela y la universidad' },
    { id: 'childhood', label: 'Los recuerdos de la infancia' },
    { id: 'future', label: 'Los planes de futuro' },
    { id: 'holidays', label: 'Las fiestas y las tradiciones' },
    { id: 'nature', label: 'La naturaleza y los animales' },
    { id: 'transport', label: 'El transporte' },
    { id: 'home', label: 'La vivienda y las reformas' },
    { id: 'restaurants', label: 'Los restaurantes y los bares' },
    { id: 'hobbies', label: 'Las aficiones' },
    { id: 'news', label: 'Las noticias' },
    { id: 'history', label: 'La historia' },
    { id: 'art', label: 'El arte y los museos' },
    { id: 'languages', label: 'Aprender idiomas' },
    { id: 'industry', label: 'La industria' },
    { id: 'infotech', label: 'La informática' },
    { id: 'ai', label: 'La inteligencia artificial' },
    { id: 'ecology', label: 'La ecología y el clima' },
    { id: 'local-es', label: 'El flamenco y la música latina' },
    { id: 'bank', label: 'En el banco', kind: 'roleplay' },
    { id: 'pharmacy', label: 'En la farmacia', kind: 'roleplay' },
    { id: 'clinic', label: 'En el médico con un resfriado', kind: 'roleplay' },
    { id: 'repair', label: 'Llamada al servicio técnico', kind: 'roleplay' },
    { id: 'office', label: 'En la oficina', kind: 'roleplay' },
    { id: 'tax', label: 'En Hacienda', kind: 'roleplay' },
    { id: 'dentist', label: 'En el dentista', kind: 'roleplay' },
    { id: 'familydoctor', label: 'En el médico de cabecera', kind: 'roleplay' },
    { id: 'pediatrician', label: 'En el pediatra', kind: 'roleplay' },
    { id: 'lab', label: 'En el laboratorio de análisis', kind: 'roleplay' },
    { id: 'jobinterview', label: 'La entrevista de trabajo', kind: 'roleplay' },
    { id: 'schoolenrol', label: 'Matricular a un hijo en el colegio', kind: 'roleplay' },
    { id: 'immigration', label: 'En la Oficina de Extranjería', kind: 'roleplay' },
  ],
  it: [
    { id: 'routine', label: 'La giornata tipo' },
    { id: 'food', label: 'Il cibo e la cucina' },
    { id: 'travel', label: 'I viaggi e le vacanze' },
    { id: 'work', label: 'Il lavoro e la carriera' },
    { id: 'family', label: 'La famiglia' },
    { id: 'friendship', label: 'L\'amicizia' },
    { id: 'city', label: 'La vita in città' },
    { id: 'sport', label: 'Lo sport' },
    { id: 'music', label: 'La musica' },
    { id: 'films', label: 'Il cinema e le serie' },
    { id: 'books', label: 'I libri e la lettura' },
    { id: 'weather', label: 'Il tempo e le stagioni' },
    { id: 'shopping', label: 'Fare la spesa e lo shopping' },
    { id: 'health', label: 'La salute e i medici' },
    { id: 'tech', label: 'La tecnologia' },
    { id: 'money', label: 'I soldi e i prezzi' },
    { id: 'school', label: 'La scuola e l\'università' },
    { id: 'childhood', label: 'I ricordi d\'infanzia' },
    { id: 'future', label: 'I progetti per il futuro' },
    { id: 'holidays', label: 'Le feste e le tradizioni' },
    { id: 'nature', label: 'La natura e gli animali' },
    { id: 'transport', label: 'I trasporti e il traffico' },
    { id: 'home', label: 'La casa e i lavori' },
    { id: 'restaurants', label: 'I ristoranti e i bar' },
    { id: 'hobbies', label: 'Gli hobby' },
    { id: 'news', label: 'Le notizie e l\'attualità' },
    { id: 'history', label: 'La storia' },
    { id: 'art', label: 'L\'arte e i musei' },
    { id: 'languages', label: 'Imparare le lingue' },
    { id: 'industry', label: "L'industria" },
    { id: 'infotech', label: "L'informatica" },
    { id: 'ai', label: "L'intelligenza artificiale" },
    { id: 'ecology', label: "L'ecologia e il clima" },
    { id: 'local-it', label: 'La cucina regionale e il caffè' },
    { id: 'bank', label: 'In banca', kind: 'roleplay' },
    { id: 'pharmacy', label: 'In farmacia', kind: 'roleplay' },
    { id: 'clinic', label: 'Dal medico con il raffreddore', kind: 'roleplay' },
    { id: 'repair', label: 'Chiamare l\'assistenza per un elettrodomestico', kind: 'roleplay' },
    { id: 'office', label: 'In ufficio', kind: 'roleplay' },
    { id: 'tax', label: "All'Agenzia delle Entrate", kind: 'roleplay' },
    { id: 'dentist', label: 'Dal dentista', kind: 'roleplay' },
    { id: 'familydoctor', label: 'Dal medico di famiglia', kind: 'roleplay' },
    { id: 'pediatrician', label: 'Dal pediatra', kind: 'roleplay' },
    { id: 'lab', label: 'Al laboratorio analisi', kind: 'roleplay' },
    { id: 'jobinterview', label: 'Il colloquio di lavoro', kind: 'roleplay' },
    { id: 'schoolenrol', label: "L'iscrizione di un figlio a scuola", kind: 'roleplay' },
    { id: 'immigration', label: 'In Questura', kind: 'roleplay' },
  ],
  pt: [
    { id: 'routine', label: 'O dia a dia' },
    { id: 'food', label: 'A comida e a cozinha' },
    { id: 'travel', label: 'As viagens e as férias' },
    { id: 'work', label: 'O trabalho e a carreira' },
    { id: 'family', label: 'A família' },
    { id: 'friendship', label: 'A amizade' },
    { id: 'city', label: 'A vida na cidade' },
    { id: 'sport', label: 'O desporto' },
    { id: 'music', label: 'A música' },
    { id: 'films', label: 'O cinema e as séries' },
    { id: 'books', label: 'Os livros e a leitura' },
    { id: 'weather', label: 'O tempo e as estações' },
    { id: 'shopping', label: 'As compras' },
    { id: 'health', label: 'A saúde e os médicos' },
    { id: 'tech', label: 'A tecnologia' },
    { id: 'money', label: 'O dinheiro e os preços' },
    { id: 'school', label: 'A escola e a universidade' },
    { id: 'childhood', label: 'As memórias de infância' },
    { id: 'future', label: 'Os planos para o futuro' },
    { id: 'holidays', label: 'As festas e as tradições' },
    { id: 'nature', label: 'A natureza e os animais' },
    { id: 'transport', label: 'Os transportes e o trânsito' },
    { id: 'home', label: 'A casa e as obras' },
    { id: 'restaurants', label: 'Os restaurantes e os cafés' },
    { id: 'hobbies', label: 'Os passatempos' },
    { id: 'news', label: 'As notícias e a atualidade' },
    { id: 'history', label: 'A história' },
    { id: 'art', label: 'A arte e os museus' },
    { id: 'languages', label: 'Aprender línguas' },
    { id: 'industry', label: 'A indústria' },
    { id: 'infotech', label: 'A informática' },
    { id: 'ai', label: 'A inteligência artificial' },
    { id: 'ecology', label: 'A ecologia e o clima' },
    { id: 'local-pt', label: 'O fado e os pastéis de nata' },
    { id: 'bank', label: 'No banco', kind: 'roleplay' },
    { id: 'pharmacy', label: 'Na farmácia', kind: 'roleplay' },
    { id: 'clinic', label: 'No médico com uma constipação', kind: 'roleplay' },
    { id: 'repair', label: 'Ligar para a assistência técnica', kind: 'roleplay' },
    { id: 'office', label: 'No escritório', kind: 'roleplay' },
    { id: 'tax', label: 'Nas Finanças', kind: 'roleplay' },
    { id: 'dentist', label: 'No dentista', kind: 'roleplay' },
    { id: 'familydoctor', label: 'No médico de família', kind: 'roleplay' },
    { id: 'pediatrician', label: 'No pediatra', kind: 'roleplay' },
    { id: 'lab', label: 'No laboratório de análises', kind: 'roleplay' },
    { id: 'jobinterview', label: 'A entrevista de emprego', kind: 'roleplay' },
    { id: 'schoolenrol', label: 'Inscrever um filho na escola', kind: 'roleplay' },
    { id: 'immigration', label: 'Na AIMA', kind: 'roleplay' },
  ],
  uk: [
    { id: 'routine', label: 'Мій день' },
    { id: 'food', label: 'Їжа та кухня' },
    { id: 'travel', label: 'Подорожі та відпустка' },
    { id: 'work', label: 'Робота та кар’єра' },
    { id: 'family', label: 'Родина' },
    { id: 'friendship', label: 'Дружба' },
    { id: 'city', label: 'Життя в місті' },
    { id: 'sport', label: 'Спорт' },
    { id: 'music', label: 'Музика' },
    { id: 'films', label: 'Кіно та серіали' },
    { id: 'books', label: 'Книжки та читання' },
    { id: 'weather', label: 'Погода та пори року' },
    { id: 'shopping', label: 'Покупки' },
    { id: 'health', label: 'Здоров’я та лікарі' },
    { id: 'tech', label: 'Технології' },
    { id: 'money', label: 'Гроші та ціни' },
    { id: 'school', label: 'Школа та університет' },
    { id: 'childhood', label: 'Спогади з дитинства' },
    { id: 'future', label: 'Плани на майбутнє' },
    { id: 'holidays', label: 'Свята та традиції' },
    { id: 'nature', label: 'Природа та тварини' },
    { id: 'transport', label: 'Транспорт' },
    { id: 'home', label: 'Дім і ремонт' },
    { id: 'restaurants', label: 'Ресторани та кав’ярні' },
    { id: 'hobbies', label: 'Захоплення' },
    { id: 'news', label: 'Новини' },
    { id: 'history', label: 'Історія' },
    { id: 'art', label: 'Мистецтво та музеї' },
    { id: 'languages', label: 'Вивчення мов' },
    { id: 'industry', label: 'Промисловість' },
    { id: 'infotech', label: 'IT і програмування' },
    { id: 'ai', label: 'Штучний інтелект' },
    { id: 'ecology', label: 'Екологія та клімат' },
    { id: 'local-uk', label: 'Борщ, вишиванка та народні пісні' },
    { id: 'bank', label: 'У банку', kind: 'roleplay' },
    { id: 'pharmacy', label: 'В аптеці', kind: 'roleplay' },
    { id: 'clinic', label: 'У лікаря із застудою', kind: 'roleplay' },
    { id: 'repair', label: 'Дзвінок у сервіс ремонту техніки', kind: 'roleplay' },
    { id: 'office', label: 'В офісі', kind: 'roleplay' },
    { id: 'tax', label: 'У податковій', kind: 'roleplay' },
    { id: 'dentist', label: 'У стоматолога', kind: 'roleplay' },
    { id: 'familydoctor', label: 'У сімейного лікаря', kind: 'roleplay' },
    { id: 'pediatrician', label: 'У педіатра', kind: 'roleplay' },
    { id: 'lab', label: 'У лабораторії аналізів', kind: 'roleplay' },
    { id: 'jobinterview', label: 'Співбесіда на роботу', kind: 'roleplay' },
    { id: 'schoolenrol', label: 'Запис дитини до школи', kind: 'roleplay' },
    { id: 'immigration', label: 'У міграційній службі', kind: 'roleplay' },
  ],
  br: [
    { id: 'routine', label: 'O dia a dia' },
    { id: 'food', label: 'A comida e a cozinha' },
    { id: 'travel', label: 'As viagens e as férias' },
    { id: 'work', label: 'O trabalho e a carreira' },
    { id: 'family', label: 'A família' },
    { id: 'friendship', label: 'A amizade' },
    { id: 'city', label: 'A vida na cidade' },
    { id: 'sport', label: 'O esporte' },
    { id: 'music', label: 'A música' },
    { id: 'films', label: 'O cinema e as séries' },
    { id: 'books', label: 'Os livros e a leitura' },
    { id: 'weather', label: 'O tempo e as estações' },
    { id: 'shopping', label: 'As compras' },
    { id: 'health', label: 'A saúde e os médicos' },
    { id: 'tech', label: 'A tecnologia' },
    { id: 'money', label: 'O dinheiro e os preços' },
    { id: 'school', label: 'A escola e a faculdade' },
    { id: 'childhood', label: 'As lembranças de infância' },
    { id: 'future', label: 'Os planos para o futuro' },
    { id: 'holidays', label: 'As festas e as tradições' },
    { id: 'nature', label: 'A natureza e os animais' },
    { id: 'transport', label: 'O trânsito e o transporte público' },
    { id: 'home', label: 'A casa e as reformas' },
    { id: 'restaurants', label: 'Os restaurantes e os botecos' },
    { id: 'hobbies', label: 'Os hobbies' },
    { id: 'news', label: 'As notícias' },
    { id: 'history', label: 'A história' },
    { id: 'art', label: 'A arte e os museus' },
    { id: 'languages', label: 'Aprender idiomas' },
    { id: 'industry', label: 'A indústria' },
    { id: 'infotech', label: 'A tecnologia da informação' },
    { id: 'ai', label: 'A inteligência artificial' },
    { id: 'ecology', label: 'A ecologia e o clima' },
    { id: 'local-br', label: 'O samba e o futebol' },
    { id: 'bank', label: 'No banco', kind: 'roleplay' },
    { id: 'pharmacy', label: 'Na farmácia', kind: 'roleplay' },
    { id: 'clinic', label: 'No médico com um resfriado', kind: 'roleplay' },
    { id: 'repair', label: 'Ligando para a assistência técnica', kind: 'roleplay' },
    { id: 'office', label: 'No escritório', kind: 'roleplay' },
    { id: 'tax', label: 'Na Receita Federal', kind: 'roleplay' },
    { id: 'dentist', label: 'No dentista', kind: 'roleplay' },
    { id: 'familydoctor', label: 'No clínico geral', kind: 'roleplay' },
    { id: 'pediatrician', label: 'No pediatra', kind: 'roleplay' },
    { id: 'lab', label: 'No laboratório de exames', kind: 'roleplay' },
    { id: 'jobinterview', label: 'A entrevista de emprego', kind: 'roleplay' },
    { id: 'schoolenrol', label: 'Matricular o filho na escola', kind: 'roleplay' },
    { id: 'immigration', label: 'Na Polícia Federal', kind: 'roleplay' },
  ],
  nl: [
    { id: 'routine', label: 'Dagelijkse routine' },
    { id: 'food', label: 'Eten en koken' },
    { id: 'travel', label: 'Reizen en vakantie' },
    { id: 'work', label: 'Werk en carrière' },
    { id: 'family', label: 'Familie' },
    { id: 'friendship', label: 'Vriendschap' },
    { id: 'city', label: 'Het leven in de stad' },
    { id: 'sport', label: 'Sport en fitness' },
    { id: 'music', label: 'Muziek' },
    { id: 'films', label: 'Films en series' },
    { id: 'books', label: 'Boeken en lezen' },
    { id: 'weather', label: 'Het weer en de seizoenen' },
    { id: 'shopping', label: 'Winkelen' },
    { id: 'health', label: 'Gezondheid en artsen' },
    { id: 'tech', label: 'Techniek en gadgets' },
    { id: 'money', label: 'Geld en prijzen' },
    { id: 'school', label: 'School en universiteit' },
    { id: 'childhood', label: 'Jeugdherinneringen' },
    { id: 'future', label: 'Plannen voor de toekomst' },
    { id: 'holidays', label: 'Feestdagen en tradities' },
    { id: 'nature', label: 'Natuur en dieren' },
    { id: 'transport', label: 'Vervoer en verkeer' },
    { id: 'home', label: 'Wonen en klussen' },
    { id: 'restaurants', label: 'Restaurants en cafés' },
    { id: 'hobbies', label: "Hobby's" },
    { id: 'news', label: 'Nieuws en actualiteit' },
    { id: 'history', label: 'Geschiedenis' },
    { id: 'art', label: 'Kunst en musea' },
    { id: 'languages', label: 'Talen leren' },
    { id: 'industry', label: 'Industrie en productie' },
    { id: 'infotech', label: 'IT en software' },
    { id: 'ai', label: 'Kunstmatige intelligentie' },
    { id: 'ecology', label: 'Ecologie en klimaat' },
    { id: 'local-nl', label: 'Fietsen, grachten en Koningsdag' },
    { id: 'bank', label: 'Bij de bank', kind: 'roleplay' },
    { id: 'pharmacy', label: 'Bij de apotheek', kind: 'roleplay' },
    { id: 'clinic', label: 'Bij de dokter met een verkoudheid', kind: 'roleplay' },
    { id: 'repair', label: 'De reparatiedienst bellen', kind: 'roleplay' },
    { id: 'office', label: 'Op kantoor', kind: 'roleplay' },
    { id: 'tax', label: 'Bij de Belastingdienst', kind: 'roleplay' },
    { id: 'dentist', label: 'Bij de tandarts', kind: 'roleplay' },
    { id: 'familydoctor', label: 'Bij de huisarts', kind: 'roleplay' },
    { id: 'pediatrician', label: 'Bij de kinderarts', kind: 'roleplay' },
    { id: 'lab', label: 'Bij het laboratorium', kind: 'roleplay' },
    { id: 'jobinterview', label: 'Het sollicitatiegesprek', kind: 'roleplay' },
    { id: 'schoolenrol', label: 'Een kind inschrijven op school', kind: 'roleplay' },
    { id: 'immigration', label: 'Bij de IND', kind: 'roleplay' },
  ],
  pl: [
    { id: 'routine', label: 'Plan dnia' },
    { id: 'food', label: 'Jedzenie i gotowanie' },
    { id: 'travel', label: 'Podróże i wakacje' },
    { id: 'work', label: 'Praca i kariera' },
    { id: 'family', label: 'Rodzina' },
    { id: 'friendship', label: 'Przyjaźń' },
    { id: 'city', label: 'Życie w mieście' },
    { id: 'sport', label: 'Sport i kondycja' },
    { id: 'music', label: 'Muzyka' },
    { id: 'films', label: 'Filmy i seriale' },
    { id: 'books', label: 'Książki i czytanie' },
    { id: 'weather', label: 'Pogoda i pory roku' },
    { id: 'shopping', label: 'Zakupy' },
    { id: 'health', label: 'Zdrowie i lekarze' },
    { id: 'tech', label: 'Technika i gadżety' },
    { id: 'money', label: 'Pieniądze i ceny' },
    { id: 'school', label: 'Szkoła i studia' },
    { id: 'childhood', label: 'Wspomnienia z dzieciństwa' },
    { id: 'future', label: 'Plany na przyszłość' },
    { id: 'holidays', label: 'Święta i tradycje' },
    { id: 'nature', label: 'Przyroda i zwierzęta' },
    { id: 'transport', label: 'Transport i korki' },
    { id: 'home', label: 'Dom i remont' },
    { id: 'restaurants', label: 'Restauracje i kawiarnie' },
    { id: 'hobbies', label: 'Hobby' },
    { id: 'news', label: 'Wiadomości i wydarzenia' },
    { id: 'history', label: 'Historia' },
    { id: 'art', label: 'Sztuka i muzea' },
    { id: 'languages', label: 'Nauka języków' },
    { id: 'industry', label: 'Przemysł' },
    { id: 'infotech', label: 'IT i programowanie' },
    { id: 'ai', label: 'Sztuczna inteligencja' },
    { id: 'ecology', label: 'Ekologia i klimat' },
    { id: 'local-pl', label: 'Pierogi, Wigilia i góry' },
    { id: 'bank', label: 'W banku', kind: 'roleplay' },
    { id: 'pharmacy', label: 'W aptece', kind: 'roleplay' },
    { id: 'clinic', label: 'U lekarza z przeziębieniem', kind: 'roleplay' },
    { id: 'repair', label: 'Telefon do serwisu AGD', kind: 'roleplay' },
    { id: 'office', label: 'W biurze', kind: 'roleplay' },
    { id: 'tax', label: 'W urzędzie skarbowym', kind: 'roleplay' },
    { id: 'dentist', label: 'U dentysty', kind: 'roleplay' },
    { id: 'familydoctor', label: 'U lekarza rodzinnego', kind: 'roleplay' },
    { id: 'pediatrician', label: 'U pediatry', kind: 'roleplay' },
    { id: 'lab', label: 'W laboratorium analiz', kind: 'roleplay' },
    { id: 'jobinterview', label: 'Rozmowa o pracę', kind: 'roleplay' },
    { id: 'schoolenrol', label: 'Zapisanie dziecka do szkoły', kind: 'roleplay' },
    { id: 'immigration', label: 'W urzędzie wojewódzkim', kind: 'roleplay' },
  ],
  ro: [
    { id: 'routine', label: 'Rutina zilnică' },
    { id: 'food', label: 'Mâncarea și gătitul' },
    { id: 'travel', label: 'Călătoriile și vacanțele' },
    { id: 'work', label: 'Munca și cariera' },
    { id: 'family', label: 'Familia' },
    { id: 'friendship', label: 'Prietenia' },
    { id: 'city', label: 'Viața la oraș' },
    { id: 'sport', label: 'Sportul și mișcarea' },
    { id: 'music', label: 'Muzica' },
    { id: 'films', label: 'Filmele și serialele' },
    { id: 'books', label: 'Cărțile și cititul' },
    { id: 'weather', label: 'Vremea și anotimpurile' },
    { id: 'shopping', label: 'Cumpărăturile' },
    { id: 'health', label: 'Sănătatea și medicii' },
    { id: 'tech', label: 'Tehnologia și gadgeturile' },
    { id: 'money', label: 'Banii și prețurile' },
    { id: 'school', label: 'Școala și facultatea' },
    { id: 'childhood', label: 'Amintiri din copilărie' },
    { id: 'future', label: 'Planurile de viitor' },
    { id: 'holidays', label: 'Sărbătorile și tradițiile' },
    { id: 'nature', label: 'Natura și animalele' },
    { id: 'transport', label: 'Transportul și traficul' },
    { id: 'home', label: 'Locuința și renovarea' },
    { id: 'restaurants', label: 'Restaurantele și cafenelele' },
    { id: 'hobbies', label: 'Hobby-urile' },
    { id: 'news', label: 'Știrile și actualitatea' },
    { id: 'history', label: 'Istoria' },
    { id: 'art', label: 'Arta și muzeele' },
    { id: 'languages', label: 'Învățarea limbilor' },
    { id: 'industry', label: 'Industria' },
    { id: 'infotech', label: 'IT-ul și programarea' },
    { id: 'ai', label: 'Inteligența artificială' },
    { id: 'ecology', label: 'Ecologia și clima' },
    { id: 'local-ro', label: 'Mămăliga, Carpații și mărțișorul' },
    { id: 'bank', label: 'La bancă', kind: 'roleplay' },
    { id: 'pharmacy', label: 'La farmacie', kind: 'roleplay' },
    { id: 'clinic', label: 'La doctor cu o răceală', kind: 'roleplay' },
    { id: 'repair', label: 'Apel la service-ul de electrocasnice', kind: 'roleplay' },
    { id: 'office', label: 'La birou', kind: 'roleplay' },
    { id: 'tax', label: 'La ANAF', kind: 'roleplay' },
    { id: 'dentist', label: 'La dentist', kind: 'roleplay' },
    { id: 'familydoctor', label: 'La medicul de familie', kind: 'roleplay' },
    { id: 'pediatrician', label: 'La pediatru', kind: 'roleplay' },
    { id: 'lab', label: 'La laboratorul de analize', kind: 'roleplay' },
    { id: 'jobinterview', label: 'Interviul de angajare', kind: 'roleplay' },
    { id: 'schoolenrol', label: 'Înscrierea copilului la școală', kind: 'roleplay' },
    { id: 'immigration', label: 'La Inspectoratul pentru Imigrări', kind: 'roleplay' },
  ],
  cs: [
    { id: 'routine', label: 'Denní režim' },
    { id: 'food', label: 'Jídlo a vaření' },
    { id: 'travel', label: 'Cestování a dovolená' },
    { id: 'work', label: 'Práce a kariéra' },
    { id: 'family', label: 'Rodina' },
    { id: 'friendship', label: 'Přátelství' },
    { id: 'city', label: 'Život ve městě' },
    { id: 'sport', label: 'Sport a kondice' },
    { id: 'music', label: 'Hudba' },
    { id: 'films', label: 'Filmy a seriály' },
    { id: 'books', label: 'Knihy a čtení' },
    { id: 'weather', label: 'Počasí a roční období' },
    { id: 'shopping', label: 'Nakupování' },
    { id: 'health', label: 'Zdraví a lékaři' },
    { id: 'tech', label: 'Technika a vychytávky' },
    { id: 'money', label: 'Peníze a ceny' },
    { id: 'school', label: 'Škola a studium' },
    { id: 'childhood', label: 'Vzpomínky na dětství' },
    { id: 'future', label: 'Plány do budoucna' },
    { id: 'holidays', label: 'Svátky a tradice' },
    { id: 'nature', label: 'Příroda a zvířata' },
    { id: 'transport', label: 'Doprava a zácpy' },
    { id: 'home', label: 'Bydlení a opravy' },
    { id: 'restaurants', label: 'Restaurace a kavárny' },
    { id: 'hobbies', label: 'Koníčky' },
    { id: 'news', label: 'Zprávy a události' },
    { id: 'history', label: 'Historie' },
    { id: 'art', label: 'Umění a muzea' },
    { id: 'languages', label: 'Studium jazyků' },
    { id: 'industry', label: 'Průmysl' },
    { id: 'infotech', label: 'IT a programování' },
    { id: 'ai', label: 'Umělá inteligence' },
    { id: 'ecology', label: 'Ekologie a klima' },
    { id: 'local-cs', label: 'Knedlíky, pivo a hrady' },
    { id: 'bank', label: 'V bance', kind: 'roleplay' },
    { id: 'pharmacy', label: 'V lékárně', kind: 'roleplay' },
    { id: 'clinic', label: 'U lékaře s nachlazením', kind: 'roleplay' },
    { id: 'repair', label: 'Telefonát do servisu spotřebičů', kind: 'roleplay' },
    { id: 'office', label: 'V kanceláři', kind: 'roleplay' },
    { id: 'tax', label: 'Na finančním úřadě', kind: 'roleplay' },
    { id: 'dentist', label: 'U zubaře', kind: 'roleplay' },
    { id: 'familydoctor', label: 'U praktického lékaře', kind: 'roleplay' },
    { id: 'pediatrician', label: 'U pediatra', kind: 'roleplay' },
    { id: 'lab', label: 'V laboratoři', kind: 'roleplay' },
    { id: 'jobinterview', label: 'Pracovní pohovor', kind: 'roleplay' },
    { id: 'schoolenrol', label: 'Zápis dítěte do školy', kind: 'roleplay' },
    { id: 'immigration', label: 'Na odboru pro cizince', kind: 'roleplay' },
  ],
};

/**
 * Фразовые глаголы — обязательная часть B2, и учить их удобнее гнездом от
 * одного глагола: get up, get over, get along. Это темы только «Слов» и только
 * английского: беседовать «о глаголе get» не о чем. Порядок — по частоте.
 */
export const PHRASAL_VERBS = [
  'get',
  'look',
  'come',
  'go',
  'take',
  'put',
  'make',
  'give',
  'turn',
  'bring',
  'break',
  'set',
  'run',
  'keep',
  'carry',
  'pick',
  'fall',
  'cut',
  'hold',
  'call',
  'work',
  'pull',
] as const;

const PHRASAL_PREFIX = 'pv-';

export const PHRASAL_TOPICS: Topic[] = PHRASAL_VERBS.map((verb) => ({
  id: `${PHRASAL_PREFIX}${verb}`,
  label: `Phrasal verbs with “${verb}”`,
  kind: 'phrasal',
}));

/** Базовый глагол темы фразовых глаголов; null — тема обычная. */
export function phrasalVerbOf(id: string | null): string | null {
  return id?.startsWith(PHRASAL_PREFIX) ? id.slice(PHRASAL_PREFIX.length) : null;
}

/**
 * Тренажёры — темы «Слов», где главное не слова, а трудное место грамматики:
 * лист сигналов и правил и упражнения на пропуск, как у фразовых глаголов.
 * Объём и тонкость — по уровню, это решает промпт.
 */
export const DRILL_TOPICS: Partial<Record<LanguageCode, Topic[]>> = {
  es: [
    { id: 'dr-subjuntivo', label: 'El subjuntivo', kind: 'drill' },
    { id: 'dr-pronombres', label: 'Le, lo, la: los pronombres', kind: 'drill' },
  ],
};

/** Темы с упражнениями на пропуск — фразовые глаголы и тренажёры. */
export function isExerciseTopic(language: LanguageCode, id: string | null): boolean {
  const topic = findTopic(language, id);
  return topic?.kind === 'phrasal' || topic?.kind === 'drill';
}

/** Группы тем с упражнениями для выбора темы в «Словах»: заголовок и темы. */
export function exerciseTopicGroups(language: LanguageCode): { title: string; topics: Topic[] }[] {
  return [
    ...(language === 'en' ? [{ title: t.sectionPhrasal, topics: PHRASAL_TOPICS }] : []),
    ...(DRILL_TOPICS[language]?.length ? [{ title: t.sectionDrills, topics: DRILL_TOPICS[language]! }] : []),
  ];
}

/** Находит тему по идентификатору — он хранится отдельно от списка. */
export function findTopic(language: LanguageCode, id: string | null): Topic | null {
  if (!id) return null;
  if (language === 'en' && phrasalVerbOf(id)) return PHRASAL_TOPICS.find((topic) => topic.id === id) ?? null;
  return (
    TOPICS[language].find((topic) => topic.id === id) ??
    DRILL_TOPICS[language]?.find((topic) => topic.id === id) ??
    null
  );
}

/**
 * Перевод названий тем на язык интерфейса. Хранится по идентификатору, а не
 * внутри темы: тема «Распорядок дня» одна и та же во всех языках, и
 * держать перевод четырежды значило бы четырежды его и править.
 */
const GLOSSES: Record<string, Record<UiLocale, string>> = {
  routine: { en: 'Daily routine', uk: 'Розпорядок дня', es: 'La rutina diaria', ru: 'Распорядок дня', de: 'Tagesablauf', fr: 'La journée type' , pt: 'O dia a dia' , zh: '日常作息', ja: '毎日の生活', ko: '하루 일과' , nl: 'Dagelijkse routine', pl: 'Plan dnia', ro: 'Rutina zilnică' },
  food: { en: 'Food and cooking', uk: 'Їжа та готування', es: 'Comida y cocina', ru: 'Еда и готовка', de: 'Essen und Kochen', fr: 'La cuisine et les repas' , pt: 'A comida e a cozinha' , zh: '饮食与烹饪', ja: '食べ物と料理', ko: '음식과 요리' , nl: 'Eten en koken', pl: 'Jedzenie i gotowanie', ro: 'Mâncarea și gătitul' },
  travel: { en: 'Travel and holidays', uk: 'Подорожі та відпустка', es: 'Viajes y vacaciones', ru: 'Путешествия и отпуск', de: 'Reisen und Urlaub', fr: 'Les voyages et les vacances' , pt: 'As viagens e as férias' , zh: '旅行与假期', ja: '旅行と休暇', ko: '여행과 휴가' , nl: 'Reizen en vakantie', pl: 'Podróże i wakacje', ro: 'Călătoriile și vacanțele' },
  work: { en: 'Work and career', uk: 'Робота та кар’єра', es: 'Trabajo y carrera', ru: 'Работа и карьера', de: 'Arbeit und Beruf', fr: 'Le travail et la carrière' , pt: 'O trabalho e a carreira' , zh: '工作与职业', ja: '仕事とキャリア', ko: '일과 직업' , nl: 'Werk en carrière', pl: 'Praca i kariera', ro: 'Munca și cariera' },
  family: { en: 'Family', uk: 'Сім’я', es: 'La familia', ru: 'Семья', de: 'Familie', fr: 'La famille' , pt: 'A família' , zh: '家庭', ja: '家族', ko: '가족' , nl: 'Familie', pl: 'Rodzina', ro: 'Familia' },
  friendship: { en: 'Friendship', uk: 'Дружба', es: 'La amistad', ru: 'Дружба', de: 'Freundschaft', fr: 'L\'amitié' , pt: 'A amizade' , zh: '友谊', ja: '友情', ko: '우정' , nl: 'Vriendschap', pl: 'Przyjaźń', ro: 'Prietenia' },
  city: { en: 'City life', uk: 'Життя у місті', es: 'La vida en la ciudad', ru: 'Жизнь в городе', de: 'Leben in der Stadt', fr: 'La vie en ville' , pt: 'A vida na cidade' , zh: '城市生活', ja: '都会の暮らし', ko: '도시 생활' , nl: 'Het leven in de stad', pl: 'Życie w mieście', ro: 'Viața la oraș' },
  sport: { en: 'Sport and fitness', uk: 'Спорт і форма', es: 'Deporte y forma física', ru: 'Спорт и форма', de: 'Sport und Fitness', fr: 'Le sport' , pt: 'O esporte' , zh: '运动与健身', ja: 'スポーツとフィットネス', ko: '운동과 건강' , nl: 'Sport en fitness', pl: 'Sport i kondycja', ro: 'Sportul și mișcarea' },
  music: { en: 'Music', uk: 'Музика', es: 'La música', ru: 'Музыка', de: 'Musik', fr: 'La musique' , pt: 'A música' , zh: '音乐', ja: '音楽', ko: '음악' , nl: 'Muziek', pl: 'Muzyka', ro: 'Muzica' },
  films: { en: 'Films and series', uk: 'Кіно та серіали', es: 'Cine y series', ru: 'Кино и сериалы', de: 'Filme und Serien', fr: 'Les films et les séries' , pt: 'O cinema e as séries' , zh: '电影与剧集', ja: '映画とドラマ', ko: '영화와 드라마' , nl: 'Films en series', pl: 'Filmy i seriale', ro: 'Filmele și serialele' },
  books: { en: 'Books and reading', uk: 'Книжки та читання', es: 'Libros y lectura', ru: 'Книги и чтение', de: 'Bücher und Lesen', fr: 'Les livres et la lecture' , pt: 'Os livros e a leitura' , zh: '书籍与阅读', ja: '本と読書', ko: '책과 독서' , nl: 'Boeken en lezen', pl: 'Książki i czytanie', ro: 'Cărțile și cititul' },
  weather: { en: 'Weather and seasons', uk: 'Погода та пори року', es: 'El tiempo y las estaciones', ru: 'Погода и времена года', de: 'Wetter und Jahreszeiten', fr: 'Le temps et les saisons' , pt: 'O tempo e as estações' , zh: '天气与季节', ja: '天気と季節', ko: '날씨와 계절' , nl: 'Het weer en de seizoenen', pl: 'Pogoda i pory roku', ro: 'Vremea și anotimpurile' },
  shopping: { en: 'Shopping', uk: 'Покупки', es: 'Las compras', ru: 'Покупки', de: 'Einkaufen', fr: 'Les courses et les achats' , pt: 'As compras' , zh: '购物', ja: '買い物', ko: '쇼핑' , nl: 'Winkelen', pl: 'Zakupy', ro: 'Cumpărăturile' },
  health: { en: 'Health and doctors', uk: 'Здоров’я та лікарі', es: 'Salud y médicos', ru: 'Здоровье и врачи', de: 'Gesundheit und Ärzte', fr: 'La santé et les médecins' , pt: 'A saúde e os médicos' , zh: '健康与看病', ja: '健康と病院', ko: '건강과 병원' , nl: 'Gezondheid en artsen', pl: 'Zdrowie i lekarze', ro: 'Sănătatea și medicii' },
  tech: { en: 'Technology and gadgets', uk: 'Техніка та гаджети', es: 'Tecnología y aparatos', ru: 'Техника и гаджеты', de: 'Technik und Geräte', fr: 'La technologie' , pt: 'A tecnologia' , zh: '科技与数码', ja: 'テクノロジーとガジェット', ko: '기술과 기기' , nl: 'Techniek en gadgets', pl: 'Technika i gadżety', ro: 'Tehnologia și gadgeturile' },
  money: { en: 'Money and prices', uk: 'Гроші та ціни', es: 'Dinero y precios', ru: 'Деньги и цены', de: 'Geld und Preise', fr: 'L\'argent et les prix' , pt: 'O dinheiro e os preços' , zh: '金钱与价格', ja: 'お金と値段', ko: '돈과 물가' , nl: 'Geld en prijzen', pl: 'Pieniądze i ceny', ro: 'Banii și prețurile' },
  school: { en: 'School and university', uk: 'Школа та університет', es: 'Escuela y universidad', ru: 'Школа и университет', de: 'Schule und Universität', fr: 'L\'école et l\'université' , pt: 'A escola e a faculdade' , zh: '学校与大学', ja: '学校と大学', ko: '학교와 대학' , nl: 'School en universiteit', pl: 'Szkoła i studia', ro: 'Școala și facultatea' },
  childhood: { en: 'Childhood memories', uk: 'Спогади дитинства', es: 'Recuerdos de la infancia', ru: 'Воспоминания о детстве', de: 'Kindheitserinnerungen', fr: 'Les souvenirs d\'enfance' , pt: 'As lembranças de infância' , zh: '童年回忆', ja: '子どもの頃の思い出', ko: '어린 시절의 추억' , nl: 'Jeugdherinneringen', pl: 'Wspomnienia z dzieciństwa', ro: 'Amintiri din copilărie' },
  future: { en: 'Plans for the future', uk: 'Плани на майбутнє', es: 'Planes de futuro', ru: 'Планы на будущее', de: 'Zukunftspläne', fr: 'Les projets d\'avenir' , pt: 'Os planos para o futuro' , zh: '未来计划', ja: '将来の計画', ko: '미래 계획' , nl: 'Plannen voor de toekomst', pl: 'Plany na przyszłość', ro: 'Planurile de viitor' },
  holidays: { en: 'Holidays and traditions', uk: 'Свята та традиції', es: 'Fiestas y tradiciones', ru: 'Праздники и традиции', de: 'Feste und Traditionen', fr: 'Les fêtes et les traditions' , pt: 'As festas e as tradições' , zh: '节日与传统', ja: '祝日と伝統', ko: '명절과 전통' , nl: 'Feestdagen en tradities', pl: 'Święta i tradycje', ro: 'Sărbătorile și tradițiile' },
  nature: { en: 'Nature and animals', uk: 'Природа та тварини', es: 'Naturaleza y animales', ru: 'Природа и животные', de: 'Natur und Tiere', fr: 'La nature et les animaux' , pt: 'A natureza e os animais' , zh: '自然与动物', ja: '自然と動物', ko: '자연과 동물' , nl: 'Natuur en dieren', pl: 'Przyroda i zwierzęta', ro: 'Natura și animalele' },
  transport: { en: 'Transport and traffic', uk: 'Транспорт і затори', es: 'Transporte y tráfico', ru: 'Транспорт и пробки', de: 'Verkehr und Bahn', fr: 'Les transports' , pt: 'O transporte e o trânsito' , zh: '交通', ja: '交通', ko: '교통' , nl: 'Vervoer en verkeer', pl: 'Transport i korki', ro: 'Transportul și traficul' },
  home: { en: 'Home and repairs', uk: 'Дім і ремонт', es: 'Vivienda y reformas', ru: 'Дом и ремонт', de: 'Wohnen und Renovieren', fr: 'Le logement et les travaux' , pt: 'A casa e as reformas' , zh: '住房与装修', ja: '住まいとリフォーム', ko: '집과 수리' , nl: 'Wonen en klussen', pl: 'Dom i remont', ro: 'Locuința și renovarea' },
  restaurants: { en: 'Restaurants and cafés', uk: 'Ресторани та кафе', es: 'Restaurantes y cafés', ru: 'Рестораны и кафе', de: 'Restaurants und Cafés', fr: 'Les restaurants et les cafés' , pt: 'Os restaurantes e os bares' , zh: '餐厅与咖啡馆', ja: 'レストランとカフェ', ko: '식당과 카페' , nl: 'Restaurants en cafés', pl: 'Restauracje i kawiarnie', ro: 'Restaurantele și cafenelele' },
  hobbies: { en: 'Hobbies', uk: 'Хобі', es: 'Aficiones', ru: 'Хобби', de: 'Hobbys', fr: 'Les loisirs' , pt: 'Os hobbies' , zh: '爱好', ja: '趣味', ko: '취미' , nl: 'Hobby\'s', pl: 'Hobby', ro: 'Hobby-urile' },
  news: { en: 'News and current events', uk: 'Новини та події', es: 'Noticias y actualidad', ru: 'Новости и события', de: 'Nachrichten und Politik', fr: 'L\'actualité' , pt: 'As notícias e a atualidade' , zh: '新闻与时事', ja: 'ニュースと時事', ko: '뉴스와 시사' , nl: 'Nieuws en actualiteit', pl: 'Wiadomości i wydarzenia', ro: 'Știrile și actualitatea' },
  history: { en: 'History', uk: 'Історія', es: 'Historia', ru: 'История', de: 'Geschichte', fr: 'L\'histoire' , pt: 'A história' , zh: '历史', ja: '歴史', ko: '역사' , nl: 'Geschiedenis', pl: 'Historia', ro: 'Istoria' },
  art: { en: 'Art and museums', uk: 'Мистецтво та музеї', es: 'Arte y museos', ru: 'Искусство и музеи', de: 'Kunst und Museen', fr: 'L\'art et les musées' , pt: 'A arte e os museus' , zh: '艺术与博物馆', ja: '芸術と美術館', ko: '예술과 박물관' , nl: 'Kunst en musea', pl: 'Sztuka i muzea', ro: 'Arta și muzeele' },
  languages: { en: 'Learning languages', uk: 'Вивчення мов', es: 'Aprender idiomas', ru: 'Изучение языков', de: 'Sprachen lernen', fr: 'L\'apprentissage des langues' , pt: 'Aprender idiomas' , zh: '学习语言', ja: '語学', ko: '언어 배우기' , nl: 'Talen leren', pl: 'Nauka języków', ro: 'Învățarea limbilor' },
  industry: { en: 'Industry and manufacturing', uk: 'Промисловість', es: 'Industria y producción', ru: 'Промышленность', de: 'Industrie und Produktion', fr: 'L\'industrie', pt: 'A indústria', zh: '工业与制造', ja: '産業とものづくり', ko: '산업과 제조' , nl: 'Industrie en productie', pl: 'Przemysł', ro: 'Industria' },
  infotech: { en: 'IT and software', uk: 'IT і програмування', es: 'Informática y software', ru: 'IT и программирование', de: 'IT und Software', fr: 'L\'informatique', pt: 'TI e software', zh: 'IT 与软件', ja: 'IT とソフトウェア', ko: 'IT와 소프트웨어' , nl: 'IT en software', pl: 'IT i programowanie', ro: 'IT-ul și programarea' },
  ai: { en: 'Artificial intelligence', uk: 'Штучний інтелект', es: 'Inteligencia artificial', ru: 'Искусственный интеллект', de: 'Künstliche Intelligenz', fr: 'L\'intelligence artificielle', pt: 'A inteligência artificial', zh: '人工智能', ja: '人工知能', ko: '인공지능' , nl: 'Kunstmatige intelligentie', pl: 'Sztuczna inteligencja', ro: 'Inteligența artificială' },
  ecology: { en: 'Ecology and climate', uk: 'Екологія та клімат', es: 'Ecología y clima', ru: 'Экология и климат', de: 'Ökologie und Klima', fr: 'L\'écologie et le climat', pt: 'A ecologia e o clima', zh: '生态与气候', ja: '環境と気候', ko: '생태와 기후' , nl: 'Ecologie en klimaat', pl: 'Ekologia i klimat', ro: 'Ecologia și clima' },

  bank: { en: 'At the bank', uk: 'У банку', es: 'En el banco', ru: 'В банке', de: 'Auf der Bank', fr: 'À la banque' , pt: 'No banco' , zh: '在银行', ja: '銀行で', ko: '은행에서' , nl: 'Bij de bank', pl: 'W banku', ro: 'La bancă' },
  pharmacy: { en: 'At the pharmacy', uk: 'В аптеці', es: 'En la farmacia', ru: 'В аптеке', de: 'In der Apotheke', fr: 'À la pharmacie' , pt: 'Na farmácia' , zh: '在药店', ja: '薬局で', ko: '약국에서' , nl: 'Bij de apotheek', pl: 'W aptece', ro: 'La farmacie' },
  clinic: { en: 'At the doctor’s: a cold', uk: 'У лікаря: застуда', es: 'En el médico: un resfriado', ru: 'У врача: простуда', de: 'Beim Arzt mit einer Erkältung', fr: 'Chez le médecin avec un rhume' , pt: 'No médico com um resfriado' , zh: '看医生：感冒', ja: '病院で：風邪', ko: '병원에서: 감기' , nl: 'Bij de dokter met een verkoudheid', pl: 'U lekarza z przeziębieniem', ro: 'La doctor cu o răceală' },
  repair: { en: 'Appliance repair service', uk: 'Ремонт побутової техніки', es: 'Reparación de electrodomésticos', ru: 'Ремонт бытовой техники', de: 'Anruf beim Reparaturdienst', fr: 'Appel au service de réparation' , pt: 'Assistência técnica de eletrodomésticos' , zh: '家电维修服务', ja: '家電の修理サービス', ko: '가전제품 수리 서비스' , nl: 'De reparatiedienst bellen', pl: 'Telefon do serwisu AGD', ro: 'Apel la service-ul de electrocasnice' },
  office: { en: 'At the office', uk: 'В офісі', es: 'En la oficina', ru: 'В офисе', de: 'Im Büro', fr: 'Au bureau', pt: 'No escritório', zh: '在办公室', ja: 'オフィスで', ko: '사무실에서' , nl: 'Op kantoor', pl: 'W biurze', ro: 'La birou' },
  tax: { en: 'At the tax office', uk: 'У податковій', es: 'En Hacienda', ru: 'В налоговой', de: 'Beim Finanzamt', fr: 'Aux impôts', pt: 'No fisco', zh: '在税务局', ja: '税務署で', ko: '세무서에서' , nl: 'Bij de Belastingdienst', pl: 'W urzędzie skarbowym', ro: 'La ANAF' },
  dentist: { en: 'At the dentist', uk: 'У стоматолога', es: 'En el dentista', ru: 'У стоматолога', de: 'Beim Zahnarzt', fr: 'Chez le dentiste', pt: 'No dentista', zh: '看牙医', ja: '歯医者で', ko: '치과에서' , nl: 'Bij de tandarts', pl: 'U dentysty', ro: 'La dentist' },
  familydoctor: { en: 'At the family doctor', uk: 'У сімейного лікаря', es: 'En el médico de cabecera', ru: 'У семейного врача', de: 'Beim Hausarzt', fr: 'Chez le médecin traitant', pt: 'No clínico geral', zh: '看家庭医生', ja: 'かかりつけ医で', ko: '가정의학과에서' , nl: 'Bij de huisarts', pl: 'U lekarza rodzinnego', ro: 'La medicul de familie' },
  pediatrician: { en: 'At the paediatrician', uk: 'У педіатра', es: 'En el pediatra', ru: 'У педиатра', de: 'Beim Kinderarzt', fr: 'Chez le pédiatre', pt: 'No pediatra', zh: '看儿科医生', ja: '小児科で', ko: '소아과에서' , nl: 'Bij de kinderarts', pl: 'U pediatry', ro: 'La pediatru' },
  lab: { en: 'At the medical lab', uk: 'У лабораторії аналізів', es: 'En el laboratorio de análisis', ru: 'В лаборатории анализов', de: 'Im Labor', fr: 'Au laboratoire d\'analyses', pt: 'No laboratório de exames', zh: '在化验室', ja: '検査センターで', ko: '검사실에서' , nl: 'Bij het laboratorium', pl: 'W laboratorium analiz', ro: 'La laboratorul de analize' },
  jobinterview: { en: 'Job interview', uk: 'Співбесіда на роботу', es: 'Entrevista de trabajo', ru: 'Собеседование на работу', de: 'Vorstellungsgespräch', fr: 'Entretien d\'embauche', pt: 'Entrevista de emprego', zh: '求职面试', ja: '就職面接', ko: '취업 면접', nl: 'Sollicitatiegesprek', pl: 'Rozmowa o pracę', ro: 'Interviul de angajare' },
  schoolenrol: { en: 'Enrolling a child at school', uk: 'Запис дитини до школи', es: 'Matricular a un hijo en el colegio', ru: 'Запись ребёнка в школу', de: 'Kind in der Schule anmelden', fr: 'Inscrire un enfant à l\'école', pt: 'Matricular o filho na escola', zh: '为孩子办理入学', ja: '子どもの入学手続き', ko: '아이 학교 입학', nl: 'Kind inschrijven op school', pl: 'Zapisanie dziecka do szkoły', ro: 'Înscrierea copilului la școală' },
  immigration: { en: 'At the immigration office', uk: 'У міграційній службі', es: 'En la oficina de extranjería', ru: 'В миграционной службе', de: 'Bei der Ausländerbehörde', fr: 'Au service des étrangers', pt: 'No serviço de imigração', zh: '在移民局', ja: '入国管理局で', ko: '출입국 사무소에서', nl: 'Bij de immigratiedienst', pl: 'W urzędzie ds. cudzoziemców', ro: 'La biroul de imigrări' },

  'dr-subjuntivo': { en: 'The Spanish subjunctive', uk: 'Субхунтив (умовний спосіб)', es: 'El subjuntivo', ru: 'Субхунтив (сослагательное наклонение)', de: 'Der Subjuntivo', fr: 'Le subjonctif espagnol', pt: 'O subjuntivo espanhol', zh: '西班牙语虚拟式', ja: 'スペイン語の接続法', ko: '스페인어 접속법', nl: 'De Spaanse subjuntivo', pl: 'Tryb subjuntivo', ro: 'Subjonctivul spaniol' },
  'dr-pronombres': { en: 'Object pronouns: le, lo, la', uk: 'Займенники додатка: le, lo, la', es: 'Pronombres de objeto: le, lo, la', ru: 'Местоимения-дополнения: le, lo, la', de: 'Objektpronomen: le, lo, la', fr: 'Pronoms compléments : le, lo, la', pt: 'Pronomes de objeto: le, lo, la', zh: '宾语代词：le、lo、la', ja: '目的格代名詞：le・lo・la', ko: '목적격 대명사: le, lo, la', nl: 'Objectvoornaamwoorden: le, lo, la', pl: 'Zaimki dopełnienia: le, lo, la', ro: 'Pronumele complement: le, lo, la' },

  'local-en': { en: 'British and American English', uk: 'Британська та американська', es: 'Inglés británico y americano', ru: 'Британский и американский', de: 'Britisches und amerikanisches Englisch', fr: 'L\'anglais britannique et américain' , pt: 'O inglês britânico e o americano' , zh: '英式英语与美式英语', ja: 'イギリス英語とアメリカ英語', ko: '영국 영어와 미국 영어' , nl: 'Brits en Amerikaans Engels', pl: 'Brytyjski i amerykański angielski', ro: 'Engleza britanică și americană' },
  'local-de': { en: 'Christmas markets and Oktoberfest', uk: 'Різдвяні ярмарки та Октоберфест', es: 'Mercados navideños y Oktoberfest', ru: 'Ярмарки и Октоберфест', de: 'Weihnachtsmärkte und Oktoberfest', fr: 'Les marchés de Noël et l’Oktoberfest' , pt: 'Mercados de Natal e Oktoberfest' , zh: '圣诞市场与啤酒节', ja: 'クリスマスマーケットとオクトーバーフェスト', ko: '크리스마스 마켓과 옥토버페스트' , nl: 'Kerstmarkten en Oktoberfest', pl: 'Jarmarki bożonarodzeniowe i Oktoberfest', ro: 'Târgurile de Crăciun și Oktoberfest' },
  'local-fr': { en: 'Cheese and wine', uk: 'Сир і вино', es: 'Queso y vino', ru: 'Сыр и вино', de: 'Käse und Wein', fr: 'Le fromage et le vin' , pt: 'Queijo e vinho' , zh: '奶酪与葡萄酒', ja: 'チーズとワイン', ko: '치즈와 와인' , nl: 'Kaas en wijn', pl: 'Ser i wino', ro: 'Brânza și vinul' },
  'local-es': { en: 'Flamenco and Latin music', uk: 'Фламенко та латинська музика', es: 'Flamenco y música latina', ru: 'Фламенко и латинская музыка', de: 'Flamenco und lateinamerikanische Musik', fr: 'Le flamenco et la musique latine' , pt: 'O flamenco e a música latina' , zh: '弗拉明戈与拉丁音乐', ja: 'フラメンコとラテン音楽', ko: '플라멩코와 라틴 음악' , nl: 'Flamenco en Latijnse muziek', pl: 'Flamenco i muzyka latynoska', ro: 'Flamenco și muzica latino' },
  'local-it': { en: 'Regional cooking and coffee', uk: 'Регіональна кухня та кава', es: 'La cocina regional y el café', ru: 'Региональная кухня и кофе', de: 'Regionale Küche und Kaffee', fr: 'La cuisine régionale et le café' , pt: 'A culinária regional e o café' , zh: '地方菜与咖啡', ja: '郷土料理とコーヒー', ko: '지역 요리와 커피' , nl: 'Regionale keuken en koffie', pl: 'Kuchnia regionalna i kawa', ro: 'Bucătăria regională și cafeaua' },
  'local-pt': { en: 'Fado and pastéis de nata', uk: 'Фаду та паштел-де-ната', es: 'El fado y los pastéis de nata', ru: 'Фаду и паштел-де-ната', de: 'Fado und Pastéis de Nata', fr: 'Le fado et les pastéis de nata' , pt: 'O fado e os pastéis de nata' , zh: '法朵与葡式蛋挞', ja: 'ファドとパステル・デ・ナタ', ko: '파두와 파스텔 드 나타' , nl: 'Fado en pastéis de nata', pl: 'Fado i pastéis de nata', ro: 'Fado și pastéis de nata' },
  'local-uk': { en: 'Borscht, vyshyvanka and folk songs', uk: 'Борщ, вишиванка та народні пісні', es: 'El borsch, la vyshyvanka y las canciones populares', ru: 'Борщ, вышиванка и народные песни', de: 'Borschtsch, Wyschywanka und Volkslieder', fr: 'Le bortsch, la vyshyvanka et les chansons populaires', pt: 'O borscht, a vyshyvanka e as canções populares' , zh: '红菜汤、刺绣衬衫与民歌', ja: 'ボルシチ、ヴィシヴァンカと民謡', ko: '보르시, 비시반카와 민요' , nl: 'Borsjt, vysjyvanka en volksliederen', pl: 'Barszcz, wyszywanka i pieśni ludowe', ro: 'Borșul, vîșîvanca și cântecele populare' },
  'local-br': { en: 'Samba and football', uk: 'Самба та футбол', es: 'La samba y el fútbol', ru: 'Самба и футбол', de: 'Samba und Fußball', fr: 'La samba et le football', pt: 'O samba e o futebol' , zh: '桑巴与足球', ja: 'サンバとサッカー', ko: '삼바와 축구' , nl: 'Samba en voetbal', pl: 'Samba i piłka nożna', ro: 'Samba și fotbalul' },
  'local-nl': { en: 'Cycling, canals and King’s Day', uk: 'Велосипеди, канали та День короля', es: 'Bicicletas, canales y el Día del Rey', ru: 'Велосипеды, каналы и День короля', de: 'Fahrräder, Grachten und Königstag', fr: 'Le vélo, les canaux et la fête du Roi', pt: 'Bicicletas, canais e o Dia do Rei', zh: '自行车、运河与国王节', ja: '自転車、運河と国王の日', ko: '자전거, 운하와 왕의 날' , nl: 'Fietsen, grachten en Koningsdag', pl: 'Rowery, kanały i Dzień Króla', ro: 'Bicicletele, canalele și Ziua Regelui' },
  'local-pl': { en: 'Pierogi, Christmas Eve and the mountains', uk: 'Вареники, Святвечір і гори', es: 'Los pierogi, la Nochebuena y las montañas', ru: 'Вареники, Сочельник и горы', de: 'Piroggen, Heiligabend und die Berge', fr: 'Les pierogi, le réveillon et la montagne', pt: 'Pierogi, a véspera de Natal e as montanhas', zh: '波兰饺子、平安夜与山', ja: 'ピエロギ、クリスマスイブと山', ko: '피에로기, 크리스마스이브와 산' , nl: 'Pierogi, kerstavond en de bergen', pl: 'Pierogi, Wigilia i góry', ro: 'Pierogi, Ajunul Crăciunului și munții' },
  'local-ro': { en: 'Mămăligă, the Carpathians and mărțișor', uk: 'Мамалига, Карпати та мерцишор', es: 'La mămăligă, los Cárpatos y el mărțișor', ru: 'Мамалыга, Карпаты и мэрцишор', de: 'Mămăligă, die Karpaten und Mărțișor', fr: 'La mămăligă, les Carpates et le mărțișor', pt: 'A mămăligă, os Cárpatos e o mărțișor', zh: '玉米粥、喀尔巴阡山与三月节', ja: 'ママリガ、カルパチア山脈とマルツィショール', ko: '마말리가, 카르파티아 산맥과 마르치쇼르' , nl: 'Mămăligă, de Karpaten en mărțișor', pl: 'Mamałyga, Karpaty i mărțișor', ro: 'Mămăliga, Carpații și mărțișorul' },
  'local-cs': { en: 'Dumplings, beer and castles', uk: 'Кнедлики, пиво та замки', es: 'Knedlíky, cerveza y castillos', ru: 'Кнедлики, пиво и замки', de: 'Knödel, Bier und Burgen', fr: 'Les knedlíky, la bière et les châteaux', pt: 'Knedlíky, cerveja e castelos', zh: '馒头片、啤酒与城堡', ja: 'クネドリーキ、ビールとお城', ko: '크네들리키, 맥주와 성', nl: 'Knedlíky, bier en kastelen', pl: 'Knedliki, piwo i zamki', ro: 'Knedlíky, bere și castele' },
};

/** Название темы на языке интерфейса; пусто, если перевода нет. */
export function topicGloss(id: string): string {
  const verb = phrasalVerbOf(id);
  if (verb) return t.phrasalTopic(verb);
  return GLOSSES[id]?.[locale] ?? '';
}
